package geostore

var timezones = []map[string]string{
	{
		"CountryCode": "AF",
		"ZoneName":    "Kabul",
		"GlobalName":  "Kabul",
		"TimeZone":    "Asia/Kabul",
		"GtmOffset":   "UTC +04:30",
	},
	{
		"CountryCode": "AL",
		"ZoneName":    "Tirane",
		"GlobalName":  "Tirane",
		"TimeZone":    "Europe/Tirane",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "DZ",
		"ZoneName":    "Algiers",
		"GlobalName":  "Algiers",
		"TimeZone":    "Africa/Algiers",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "AS",
		"ZoneName":    "Pago Pago",
		"GlobalName":  "Pago Pago",
		"TimeZone":    "Pacific/Pago_Pago",
		"GtmOffset":   "UTC -11:00",
	},
	{
		"CountryCode": "AD",
		"ZoneName":    "Andorra",
		"GlobalName":  "Andorra",
		"TimeZone":    "Europe/Andorra",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "AO",
		"ZoneName":    "Luanda",
		"GlobalName":  "Luanda",
		"TimeZone":    "Africa/Luanda",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "AI",
		"ZoneName":    "Anguilla",
		"GlobalName":  "Anguilla",
		"TimeZone":    "America/Anguilla",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Casey",
		"GlobalName":  "Casey",
		"TimeZone":    "Antarctica/Casey",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Davis",
		"GlobalName":  "Davis",
		"TimeZone":    "Antarctica/Davis",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "DumontDUrville",
		"GlobalName":  "DumontDUrville",
		"TimeZone":    "Antarctica/DumontDUrville",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Mawson",
		"GlobalName":  "Mawson",
		"TimeZone":    "Antarctica/Mawson",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "McMurdo",
		"GlobalName":  "McMurdo",
		"TimeZone":    "Antarctica/McMurdo",
		"GtmOffset":   "UTC +13:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Palmer",
		"GlobalName":  "Palmer",
		"TimeZone":    "Antarctica/Palmer",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Rothera",
		"GlobalName":  "Rothera",
		"TimeZone":    "Antarctica/Rothera",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Syowa",
		"GlobalName":  "Syowa",
		"TimeZone":    "Antarctica/Syowa",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Troll",
		"GlobalName":  "Troll",
		"TimeZone":    "Antarctica/Troll",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "AQ",
		"ZoneName":    "Vostok",
		"GlobalName":  "Vostok",
		"TimeZone":    "Antarctica/Vostok",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "AG",
		"ZoneName":    "Antigua",
		"GlobalName":  "Antigua",
		"TimeZone":    "America/Antigua",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Buenos Aires",
		"GlobalName":  "Buenos Aires",
		"TimeZone":    "America/Argentina/Buenos_Aires",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Catamarca",
		"GlobalName":  "Catamarca",
		"TimeZone":    "America/Argentina/Catamarca",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Cordoba",
		"GlobalName":  "Cordoba",
		"TimeZone":    "America/Argentina/Cordoba",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Jujuy",
		"GlobalName":  "Jujuy",
		"TimeZone":    "America/Argentina/Jujuy",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "La Rioja",
		"GlobalName":  "La Rioja",
		"TimeZone":    "America/Argentina/La_Rioja",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Mendoza",
		"GlobalName":  "Mendoza",
		"TimeZone":    "America/Argentina/Mendoza",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Rio Gallegos",
		"GlobalName":  "Rio Gallegos",
		"TimeZone":    "America/Argentina/Rio_Gallegos",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Salta",
		"GlobalName":  "Salta",
		"TimeZone":    "America/Argentina/Salta",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "San Juan",
		"GlobalName":  "San Juan",
		"TimeZone":    "America/Argentina/San_Juan",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "San Luis",
		"GlobalName":  "San Luis",
		"TimeZone":    "America/Argentina/San_Luis",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Tucuman",
		"GlobalName":  "Tucuman",
		"TimeZone":    "America/Argentina/Tucuman",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AR",
		"ZoneName":    "Ushuaia",
		"GlobalName":  "Ushuaia",
		"TimeZone":    "America/Argentina/Ushuaia",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "AM",
		"ZoneName":    "Yerevan",
		"GlobalName":  "Yerevan",
		"TimeZone":    "Asia/Yerevan",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "AW",
		"ZoneName":    "Aruba",
		"GlobalName":  "Aruba",
		"TimeZone":    "America/Aruba",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Macquarie",
		"GlobalName":  "Macquarie",
		"TimeZone":    "Antarctica/Macquarie",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Adelaide",
		"GlobalName":  "Adelaide",
		"TimeZone":    "Australia/Adelaide",
		"GtmOffset":   "UTC +10:30",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Brisbane",
		"GlobalName":  "Brisbane",
		"TimeZone":    "Australia/Brisbane",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Broken Hill",
		"GlobalName":  "Broken Hill",
		"TimeZone":    "Australia/Broken_Hill",
		"GtmOffset":   "UTC +10:30",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Currie",
		"GlobalName":  "Currie",
		"TimeZone":    "Australia/Currie",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Darwin",
		"GlobalName":  "Darwin",
		"TimeZone":    "Australia/Darwin",
		"GtmOffset":   "UTC +09:30",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Eucla",
		"GlobalName":  "Eucla",
		"TimeZone":    "Australia/Eucla",
		"GtmOffset":   "UTC +08:45",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Hobart",
		"GlobalName":  "Hobart",
		"TimeZone":    "Australia/Hobart",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Lindeman",
		"GlobalName":  "Lindeman",
		"TimeZone":    "Australia/Lindeman",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Lord Howe",
		"GlobalName":  "Lord Howe",
		"TimeZone":    "Australia/Lord_Howe",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Melbourne",
		"GlobalName":  "Melbourne",
		"TimeZone":    "Australia/Melbourne",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Perth",
		"GlobalName":  "Perth",
		"TimeZone":    "Australia/Perth",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "AU",
		"ZoneName":    "Sydney",
		"GlobalName":  "Sydney",
		"TimeZone":    "Australia/Sydney",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "AT",
		"ZoneName":    "Vienna",
		"GlobalName":  "Vienna",
		"TimeZone":    "Europe/Vienna",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "AZ",
		"ZoneName":    "Baku",
		"GlobalName":  "Baku",
		"TimeZone":    "Asia/Baku",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "BS",
		"ZoneName":    "Nassau",
		"GlobalName":  "Nassau",
		"TimeZone":    "America/Nassau",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "BH",
		"ZoneName":    "Bahrain",
		"GlobalName":  "Bahrain",
		"TimeZone":    "Asia/Bahrain",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "BD",
		"ZoneName":    "Dhaka",
		"GlobalName":  "Dhaka",
		"TimeZone":    "Asia/Dhaka",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "BB",
		"ZoneName":    "Barbados",
		"GlobalName":  "Barbados",
		"TimeZone":    "America/Barbados",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BY",
		"ZoneName":    "Minsk",
		"GlobalName":  "Minsk",
		"TimeZone":    "Europe/Minsk",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "BE",
		"ZoneName":    "Brussels",
		"GlobalName":  "Brussels",
		"TimeZone":    "Europe/Brussels",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "BZ",
		"ZoneName":    "Belize",
		"GlobalName":  "Belize",
		"TimeZone":    "America/Belize",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "BJ",
		"ZoneName":    "Porto-Novo",
		"GlobalName":  "Porto-Novo",
		"TimeZone":    "Africa/Porto-Novo",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "BM",
		"ZoneName":    "Bermuda",
		"GlobalName":  "Bermuda",
		"TimeZone":    "Atlantic/Bermuda",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BT",
		"ZoneName":    "Thimphu",
		"GlobalName":  "Thimphu",
		"TimeZone":    "Asia/Thimphu",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "BO",
		"ZoneName":    "La Paz",
		"GlobalName":  "La Paz",
		"TimeZone":    "America/La_Paz",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BQ",
		"ZoneName":    "Kralendijk",
		"GlobalName":  "Kralendijk",
		"TimeZone":    "America/Kralendijk",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BA",
		"ZoneName":    "Sarajevo",
		"GlobalName":  "Sarajevo",
		"TimeZone":    "Europe/Sarajevo",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "BW",
		"ZoneName":    "Gaborone",
		"GlobalName":  "Gaborone",
		"TimeZone":    "Africa/Gaborone",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Araguaina",
		"GlobalName":  "Araguaina",
		"TimeZone":    "America/Araguaina",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Bahia",
		"GlobalName":  "Bahia",
		"TimeZone":    "America/Bahia",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Belem",
		"GlobalName":  "Belem",
		"TimeZone":    "America/Belem",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Boa Vista",
		"GlobalName":  "Boa Vista",
		"TimeZone":    "America/Boa_Vista",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Campo Grande",
		"GlobalName":  "Campo Grande",
		"TimeZone":    "America/Campo_Grande",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Cuiaba",
		"GlobalName":  "Cuiaba",
		"TimeZone":    "America/Cuiaba",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Eirunepe",
		"GlobalName":  "Eirunepe",
		"TimeZone":    "America/Eirunepe",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Fortaleza",
		"GlobalName":  "Fortaleza",
		"TimeZone":    "America/Fortaleza",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Maceio",
		"GlobalName":  "Maceio",
		"TimeZone":    "America/Maceio",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Manaus",
		"GlobalName":  "Manaus",
		"TimeZone":    "America/Manaus",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Noronha",
		"GlobalName":  "Noronha",
		"TimeZone":    "America/Noronha",
		"GtmOffset":   "UTC -02:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Porto Velho",
		"GlobalName":  "Porto Velho",
		"TimeZone":    "America/Porto_Velho",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Recife",
		"GlobalName":  "Recife",
		"TimeZone":    "America/Recife",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Rio Branco",
		"GlobalName":  "Rio Branco",
		"TimeZone":    "America/Rio_Branco",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Santarem",
		"GlobalName":  "Santarem",
		"TimeZone":    "America/Santarem",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "BR",
		"ZoneName":    "Sao Paulo",
		"GlobalName":  "Sao Paulo",
		"TimeZone":    "America/Sao_Paulo",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "IO",
		"ZoneName":    "Chagos",
		"GlobalName":  "Chagos",
		"TimeZone":    "Indian/Chagos",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "BN",
		"ZoneName":    "Brunei",
		"GlobalName":  "Brunei",
		"TimeZone":    "Asia/Brunei",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "BG",
		"ZoneName":    "Sofia",
		"GlobalName":  "Sofia",
		"TimeZone":    "Europe/Sofia",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "BF",
		"ZoneName":    "Ouagadougou",
		"GlobalName":  "Ouagadougou",
		"TimeZone":    "Africa/Ouagadougou",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "BI",
		"ZoneName":    "Bujumbura",
		"GlobalName":  "Bujumbura",
		"TimeZone":    "Africa/Bujumbura",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "KH",
		"ZoneName":    "Phnom Penh",
		"GlobalName":  "Phnom Penh",
		"TimeZone":    "Asia/Phnom_Penh",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "CM",
		"ZoneName":    "Douala",
		"GlobalName":  "Douala",
		"TimeZone":    "Africa/Douala",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Atikokan",
		"GlobalName":  "Atikokan",
		"TimeZone":    "America/Atikokan",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Blanc-Sablon",
		"GlobalName":  "Blanc-Sablon",
		"TimeZone":    "America/Blanc-Sablon",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Cambridge Bay",
		"GlobalName":  "Cambridge Bay",
		"TimeZone":    "America/Cambridge_Bay",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Creston",
		"GlobalName":  "Creston",
		"TimeZone":    "America/Creston",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Dawson",
		"GlobalName":  "Dawson",
		"TimeZone":    "America/Dawson",
		"GtmOffset":   "UTC -08:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Dawson Creek",
		"GlobalName":  "Dawson Creek",
		"TimeZone":    "America/Dawson_Creek",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Edmonton",
		"GlobalName":  "Edmonton",
		"TimeZone":    "America/Edmonton",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Fort Nelson",
		"GlobalName":  "Fort Nelson",
		"TimeZone":    "America/Fort_Nelson",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Glace Bay",
		"GlobalName":  "Glace Bay",
		"TimeZone":    "America/Glace_Bay",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Goose Bay",
		"GlobalName":  "Goose Bay",
		"TimeZone":    "America/Goose_Bay",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Halifax",
		"GlobalName":  "Halifax",
		"TimeZone":    "America/Halifax",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Inuvik",
		"GlobalName":  "Inuvik",
		"TimeZone":    "America/Inuvik",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Iqaluit",
		"GlobalName":  "Iqaluit",
		"TimeZone":    "America/Iqaluit",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Moncton",
		"GlobalName":  "Moncton",
		"TimeZone":    "America/Moncton",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Nipigon",
		"GlobalName":  "Nipigon",
		"TimeZone":    "America/Nipigon",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Pangnirtung",
		"GlobalName":  "Pangnirtung",
		"TimeZone":    "America/Pangnirtung",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Rainy River",
		"GlobalName":  "Rainy River",
		"TimeZone":    "America/Rainy_River",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Rankin Inlet",
		"GlobalName":  "Rankin Inlet",
		"TimeZone":    "America/Rankin_Inlet",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Regina",
		"GlobalName":  "Regina",
		"TimeZone":    "America/Regina",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Resolute",
		"GlobalName":  "Resolute",
		"TimeZone":    "America/Resolute",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "St Johns",
		"GlobalName":  "St Johns",
		"TimeZone":    "America/St_Johns",
		"GtmOffset":   "UTC -03:30",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Swift Current",
		"GlobalName":  "Swift Current",
		"TimeZone":    "America/Swift_Current",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Thunder Bay",
		"GlobalName":  "Thunder Bay",
		"TimeZone":    "America/Thunder_Bay",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Toronto",
		"GlobalName":  "Toronto",
		"TimeZone":    "America/Toronto",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Vancouver",
		"GlobalName":  "Vancouver",
		"TimeZone":    "America/Vancouver",
		"GtmOffset":   "UTC -08:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Whitehorse",
		"GlobalName":  "Whitehorse",
		"TimeZone":    "America/Whitehorse",
		"GtmOffset":   "UTC -08:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Winnipeg",
		"GlobalName":  "Winnipeg",
		"TimeZone":    "America/Winnipeg",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "CA",
		"ZoneName":    "Yellowknife",
		"GlobalName":  "Yellowknife",
		"TimeZone":    "America/Yellowknife",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "CV",
		"ZoneName":    "Cape Verde",
		"GlobalName":  "Cape Verde",
		"TimeZone":    "Atlantic/Cape_Verde",
		"GtmOffset":   "UTC -01:00",
	},
	{
		"CountryCode": "KY",
		"ZoneName":    "Cayman",
		"GlobalName":  "Cayman",
		"TimeZone":    "America/Cayman",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CF",
		"ZoneName":    "Bangui",
		"GlobalName":  "Bangui",
		"TimeZone":    "Africa/Bangui",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "TD",
		"ZoneName":    "Ndjamena",
		"GlobalName":  "Ndjamena",
		"TimeZone":    "Africa/Ndjamena",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CL",
		"ZoneName":    "Punta Arenas",
		"GlobalName":  "Punta Arenas",
		"TimeZone":    "America/Punta_Arenas",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "CL",
		"ZoneName":    "Santiago",
		"GlobalName":  "Santiago",
		"TimeZone":    "America/Santiago",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "CL",
		"ZoneName":    "Easter",
		"GlobalName":  "Easter",
		"TimeZone":    "Pacific/Easter",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CN",
		"ZoneName":    "Shanghai",
		"GlobalName":  "Shanghai",
		"TimeZone":    "Asia/Shanghai",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "CN",
		"ZoneName":    "Urumqi",
		"GlobalName":  "Urumqi",
		"TimeZone":    "Asia/Urumqi",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "CX",
		"ZoneName":    "Christmas",
		"GlobalName":  "Christmas",
		"TimeZone":    "Indian/Christmas",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "CC",
		"ZoneName":    "Cocos",
		"GlobalName":  "Cocos",
		"TimeZone":    "Indian/Cocos",
		"GtmOffset":   "UTC +06:30",
	},
	{
		"CountryCode": "CO",
		"ZoneName":    "Bogota",
		"GlobalName":  "Bogota",
		"TimeZone":    "America/Bogota",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "KM",
		"ZoneName":    "Comoro",
		"GlobalName":  "Comoro",
		"TimeZone":    "Indian/Comoro",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "CG",
		"ZoneName":    "Brazzaville",
		"GlobalName":  "Brazzaville",
		"TimeZone":    "Africa/Brazzaville",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CD",
		"ZoneName":    "Kinshasa",
		"GlobalName":  "Kinshasa",
		"TimeZone":    "Africa/Kinshasa",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CD",
		"ZoneName":    "Lubumbashi",
		"GlobalName":  "Lubumbashi",
		"TimeZone":    "Africa/Lubumbashi",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "CK",
		"ZoneName":    "Rarotonga",
		"GlobalName":  "Rarotonga",
		"TimeZone":    "Pacific/Rarotonga",
		"GtmOffset":   "UTC -10:00",
	},
	{
		"CountryCode": "CR",
		"ZoneName":    "Costa Rica",
		"GlobalName":  "Costa Rica",
		"TimeZone":    "America/Costa_Rica",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "HR",
		"ZoneName":    "Zagreb",
		"GlobalName":  "Zagreb",
		"TimeZone":    "Europe/Zagreb",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CU",
		"ZoneName":    "Havana",
		"GlobalName":  "Havana",
		"TimeZone":    "America/Havana",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "CW",
		"ZoneName":    "Curacao",
		"GlobalName":  "Curacao",
		"TimeZone":    "America/Curacao",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "CY",
		"ZoneName":    "Famagusta",
		"GlobalName":  "Famagusta",
		"TimeZone":    "Asia/Famagusta",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "CY",
		"ZoneName":    "Nicosia",
		"GlobalName":  "Nicosia",
		"TimeZone":    "Asia/Nicosia",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "CZ",
		"ZoneName":    "Prague",
		"GlobalName":  "Prague",
		"TimeZone":    "Europe/Prague",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CI",
		"ZoneName":    "Abidjan",
		"GlobalName":  "Abidjan",
		"TimeZone":    "Africa/Abidjan",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "DK",
		"ZoneName":    "Copenhagen",
		"GlobalName":  "Copenhagen",
		"TimeZone":    "Europe/Copenhagen",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "DJ",
		"ZoneName":    "Djibouti",
		"GlobalName":  "Djibouti",
		"TimeZone":    "Africa/Djibouti",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "DM",
		"ZoneName":    "Dominica",
		"GlobalName":  "Dominica",
		"TimeZone":    "America/Dominica",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "DO",
		"ZoneName":    "Santo Domingo",
		"GlobalName":  "Santo Domingo",
		"TimeZone":    "America/Santo_Domingo",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "EC",
		"ZoneName":    "Guayaquil",
		"GlobalName":  "Guayaquil",
		"TimeZone":    "America/Guayaquil",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "EC",
		"ZoneName":    "Galapagos",
		"GlobalName":  "Galapagos",
		"TimeZone":    "Pacific/Galapagos",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "EG",
		"ZoneName":    "Cairo",
		"GlobalName":  "Cairo",
		"TimeZone":    "Africa/Cairo",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "SV",
		"ZoneName":    "El Salvador",
		"GlobalName":  "El Salvador",
		"TimeZone":    "America/El_Salvador",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "GQ",
		"ZoneName":    "Malabo",
		"GlobalName":  "Malabo",
		"TimeZone":    "Africa/Malabo",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "ER",
		"ZoneName":    "Asmara",
		"GlobalName":  "Asmara",
		"TimeZone":    "Africa/Asmara",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "EE",
		"ZoneName":    "Tallinn",
		"GlobalName":  "Tallinn",
		"TimeZone":    "Europe/Tallinn",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "ET",
		"ZoneName":    "Addis Ababa",
		"GlobalName":  "Addis Ababa",
		"TimeZone":    "Africa/Addis_Ababa",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "FK",
		"ZoneName":    "Stanley",
		"GlobalName":  "Stanley",
		"TimeZone":    "Atlantic/Stanley",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "FO",
		"ZoneName":    "Faroe",
		"GlobalName":  "Faroe",
		"TimeZone":    "Atlantic/Faroe",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "FJ",
		"ZoneName":    "Fiji",
		"GlobalName":  "Fiji",
		"TimeZone":    "Pacific/Fiji",
		"GtmOffset":   "UTC +13:00",
	},
	{
		"CountryCode": "FI",
		"ZoneName":    "Helsinki",
		"GlobalName":  "Helsinki",
		"TimeZone":    "Europe/Helsinki",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "FR",
		"ZoneName":    "Paris",
		"GlobalName":  "Paris",
		"TimeZone":    "Europe/Paris",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "GF",
		"ZoneName":    "Cayenne",
		"GlobalName":  "Cayenne",
		"TimeZone":    "America/Cayenne",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "PF",
		"ZoneName":    "Gambier",
		"GlobalName":  "Gambier",
		"TimeZone":    "Pacific/Gambier",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "PF",
		"ZoneName":    "Marquesas",
		"GlobalName":  "Marquesas",
		"TimeZone":    "Pacific/Marquesas",
		"GtmOffset":   "UTC -09:30",
	},
	{
		"CountryCode": "PF",
		"ZoneName":    "Tahiti",
		"GlobalName":  "Tahiti",
		"TimeZone":    "Pacific/Tahiti",
		"GtmOffset":   "UTC -10:00",
	},
	{
		"CountryCode": "TF",
		"ZoneName":    "Kerguelen",
		"GlobalName":  "Kerguelen",
		"TimeZone":    "Indian/Kerguelen",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "GA",
		"ZoneName":    "Libreville",
		"GlobalName":  "Libreville",
		"TimeZone":    "Africa/Libreville",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "GM",
		"ZoneName":    "Banjul",
		"GlobalName":  "Banjul",
		"TimeZone":    "Africa/Banjul",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "GE",
		"ZoneName":    "Tbilisi",
		"GlobalName":  "Tbilisi",
		"TimeZone":    "Asia/Tbilisi",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "DE",
		"ZoneName":    "Berlin",
		"GlobalName":  "Berlin",
		"TimeZone":    "Europe/Berlin",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "DE",
		"ZoneName":    "Busingen",
		"GlobalName":  "Busingen",
		"TimeZone":    "Europe/Busingen",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "GH",
		"ZoneName":    "Accra",
		"GlobalName":  "Accra",
		"TimeZone":    "Africa/Accra",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "GI",
		"ZoneName":    "Gibraltar",
		"GlobalName":  "Gibraltar",
		"TimeZone":    "Europe/Gibraltar",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "GR",
		"ZoneName":    "Athens",
		"GlobalName":  "Athens",
		"TimeZone":    "Europe/Athens",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "GL",
		"ZoneName":    "Danmarkshavn",
		"GlobalName":  "Danmarkshavn",
		"TimeZone":    "America/Danmarkshavn",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "GL",
		"ZoneName":    "Godthab",
		"GlobalName":  "Godthab",
		"TimeZone":    "America/Godthab",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "GL",
		"ZoneName":    "Scoresbysund",
		"GlobalName":  "Scoresbysund",
		"TimeZone":    "America/Scoresbysund",
		"GtmOffset":   "UTC -01:00",
	},
	{
		"CountryCode": "GL",
		"ZoneName":    "Thule",
		"GlobalName":  "Thule",
		"TimeZone":    "America/Thule",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "GD",
		"ZoneName":    "Grenada",
		"GlobalName":  "Grenada",
		"TimeZone":    "America/Grenada",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "GP",
		"ZoneName":    "Guadeloupe",
		"GlobalName":  "Guadeloupe",
		"TimeZone":    "America/Guadeloupe",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "GU",
		"ZoneName":    "Guam",
		"GlobalName":  "Guam",
		"TimeZone":    "Pacific/Guam",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "GT",
		"ZoneName":    "Guatemala",
		"GlobalName":  "Guatemala",
		"TimeZone":    "America/Guatemala",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "GG",
		"ZoneName":    "Guernsey",
		"GlobalName":  "Guernsey",
		"TimeZone":    "Europe/Guernsey",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "GN",
		"ZoneName":    "Conakry",
		"GlobalName":  "Conakry",
		"TimeZone":    "Africa/Conakry",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "GW",
		"ZoneName":    "Bissau",
		"GlobalName":  "Bissau",
		"TimeZone":    "Africa/Bissau",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "GY",
		"ZoneName":    "Guyana",
		"GlobalName":  "Guyana",
		"TimeZone":    "America/Guyana",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "HT",
		"ZoneName":    "Port-au-Prince",
		"GlobalName":  "Port-au-Prince",
		"TimeZone":    "America/Port-au-Prince",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "VA",
		"ZoneName":    "Vatican",
		"GlobalName":  "Vatican",
		"TimeZone":    "Europe/Vatican",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "HN",
		"ZoneName":    "Tegucigalpa",
		"GlobalName":  "Tegucigalpa",
		"TimeZone":    "America/Tegucigalpa",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "HK",
		"ZoneName":    "Hong Kong",
		"GlobalName":  "Hong Kong",
		"TimeZone":    "Asia/Hong_Kong",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "HU",
		"ZoneName":    "Budapest",
		"GlobalName":  "Budapest",
		"TimeZone":    "Europe/Budapest",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "IS",
		"ZoneName":    "Reykjavik",
		"GlobalName":  "Reykjavik",
		"TimeZone":    "Atlantic/Reykjavik",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "IN",
		"ZoneName":    "Kolkata",
		"GlobalName":  "Kolkata",
		"TimeZone":    "Asia/Kolkata",
		"GtmOffset":   "UTC +05:30",
	},
	{
		"CountryCode": "ID",
		"ZoneName":    "Jakarta",
		"GlobalName":  "Jakarta",
		"TimeZone":    "Asia/Jakarta",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "ID",
		"ZoneName":    "Jayapura",
		"GlobalName":  "Jayapura",
		"TimeZone":    "Asia/Jayapura",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "ID",
		"ZoneName":    "Makassar",
		"GlobalName":  "Makassar",
		"TimeZone":    "Asia/Makassar",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "ID",
		"ZoneName":    "Pontianak",
		"GlobalName":  "Pontianak",
		"TimeZone":    "Asia/Pontianak",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "IR",
		"ZoneName":    "Tehran",
		"GlobalName":  "Tehran",
		"TimeZone":    "Asia/Tehran",
		"GtmOffset":   "UTC +03:30",
	},
	{
		"CountryCode": "IQ",
		"ZoneName":    "Baghdad",
		"GlobalName":  "Baghdad",
		"TimeZone":    "Asia/Baghdad",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "IE",
		"ZoneName":    "Dublin",
		"GlobalName":  "Dublin",
		"TimeZone":    "Europe/Dublin",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "IM",
		"ZoneName":    "Isle of_Man",
		"GlobalName":  "Isle of_Man",
		"TimeZone":    "Europe/Isle_of_Man",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "IL",
		"ZoneName":    "Jerusalem",
		"GlobalName":  "Jerusalem",
		"TimeZone":    "Asia/Jerusalem",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "IT",
		"ZoneName":    "Rome",
		"GlobalName":  "Rome",
		"TimeZone":    "Europe/Rome",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "JM",
		"ZoneName":    "Jamaica",
		"GlobalName":  "Jamaica",
		"TimeZone":    "America/Jamaica",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "JP",
		"ZoneName":    "Tokyo",
		"GlobalName":  "Tokyo",
		"TimeZone":    "Asia/Tokyo",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "JE",
		"ZoneName":    "Jersey",
		"GlobalName":  "Jersey",
		"TimeZone":    "Europe/Jersey",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "JO",
		"ZoneName":    "Amman",
		"GlobalName":  "Amman",
		"TimeZone":    "Asia/Amman",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Almaty",
		"GlobalName":  "Almaty",
		"TimeZone":    "Asia/Almaty",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Aqtau",
		"GlobalName":  "Aqtau",
		"TimeZone":    "Asia/Aqtau",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Aqtobe",
		"GlobalName":  "Aqtobe",
		"TimeZone":    "Asia/Aqtobe",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Atyrau",
		"GlobalName":  "Atyrau",
		"TimeZone":    "Asia/Atyrau",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Oral",
		"GlobalName":  "Oral",
		"TimeZone":    "Asia/Oral",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Qostanay",
		"GlobalName":  "Qostanay",
		"TimeZone":    "Asia/Qostanay",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "KZ",
		"ZoneName":    "Qyzylorda",
		"GlobalName":  "Qyzylorda",
		"TimeZone":    "Asia/Qyzylorda",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "KE",
		"ZoneName":    "Nairobi",
		"GlobalName":  "Nairobi",
		"TimeZone":    "Africa/Nairobi",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "KI",
		"ZoneName":    "Enderbury",
		"GlobalName":  "Enderbury",
		"TimeZone":    "Pacific/Enderbury",
		"GtmOffset":   "UTC +13:00",
	},
	{
		"CountryCode": "KI",
		"ZoneName":    "Kiritimati",
		"GlobalName":  "Kiritimati",
		"TimeZone":    "Pacific/Kiritimati",
		"GtmOffset":   "UTC +14:00",
	},
	{
		"CountryCode": "KI",
		"ZoneName":    "Tarawa",
		"GlobalName":  "Tarawa",
		"TimeZone":    "Pacific/Tarawa",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "KP",
		"ZoneName":    "Pyongyang",
		"GlobalName":  "Pyongyang",
		"TimeZone":    "Asia/Pyongyang",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "KR",
		"ZoneName":    "Seoul",
		"GlobalName":  "Seoul",
		"TimeZone":    "Asia/Seoul",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "KW",
		"ZoneName":    "Kuwait",
		"GlobalName":  "Kuwait",
		"TimeZone":    "Asia/Kuwait",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "KG",
		"ZoneName":    "Bishkek",
		"GlobalName":  "Bishkek",
		"TimeZone":    "Asia/Bishkek",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "LA",
		"ZoneName":    "Vientiane",
		"GlobalName":  "Vientiane",
		"TimeZone":    "Asia/Vientiane",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "LV",
		"ZoneName":    "Riga",
		"GlobalName":  "Riga",
		"TimeZone":    "Europe/Riga",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "LB",
		"ZoneName":    "Beirut",
		"GlobalName":  "Beirut",
		"TimeZone":    "Asia/Beirut",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "LS",
		"ZoneName":    "Maseru",
		"GlobalName":  "Maseru",
		"TimeZone":    "Africa/Maseru",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "LR",
		"ZoneName":    "Monrovia",
		"GlobalName":  "Monrovia",
		"TimeZone":    "Africa/Monrovia",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "LY",
		"ZoneName":    "Tripoli",
		"GlobalName":  "Tripoli",
		"TimeZone":    "Africa/Tripoli",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "LI",
		"ZoneName":    "Vaduz",
		"GlobalName":  "Vaduz",
		"TimeZone":    "Europe/Vaduz",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "LT",
		"ZoneName":    "Vilnius",
		"GlobalName":  "Vilnius",
		"TimeZone":    "Europe/Vilnius",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "LU",
		"ZoneName":    "Luxembourg",
		"GlobalName":  "Luxembourg",
		"TimeZone":    "Europe/Luxembourg",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "MO",
		"ZoneName":    "Macau",
		"GlobalName":  "Macau",
		"TimeZone":    "Asia/Macau",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "MK",
		"ZoneName":    "Skopje",
		"GlobalName":  "Skopje",
		"TimeZone":    "Europe/Skopje",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "MG",
		"ZoneName":    "Antananarivo",
		"GlobalName":  "Antananarivo",
		"TimeZone":    "Indian/Antananarivo",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "MW",
		"ZoneName":    "Blantyre",
		"GlobalName":  "Blantyre",
		"TimeZone":    "Africa/Blantyre",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "MY",
		"ZoneName":    "Kuala Lumpur",
		"GlobalName":  "Kuala Lumpur",
		"TimeZone":    "Asia/Kuala_Lumpur",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "MY",
		"ZoneName":    "Kuching",
		"GlobalName":  "Kuching",
		"TimeZone":    "Asia/Kuching",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "MV",
		"ZoneName":    "Maldives",
		"GlobalName":  "Maldives",
		"TimeZone":    "Indian/Maldives",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "ML",
		"ZoneName":    "Bamako",
		"GlobalName":  "Bamako",
		"TimeZone":    "Africa/Bamako",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "MT",
		"ZoneName":    "Malta",
		"GlobalName":  "Malta",
		"TimeZone":    "Europe/Malta",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "MH",
		"ZoneName":    "Kwajalein",
		"GlobalName":  "Kwajalein",
		"TimeZone":    "Pacific/Kwajalein",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "MH",
		"ZoneName":    "Majuro",
		"GlobalName":  "Majuro",
		"TimeZone":    "Pacific/Majuro",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "MQ",
		"ZoneName":    "Martinique",
		"GlobalName":  "Martinique",
		"TimeZone":    "America/Martinique",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "MR",
		"ZoneName":    "Nouakchott",
		"GlobalName":  "Nouakchott",
		"TimeZone":    "Africa/Nouakchott",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "MU",
		"ZoneName":    "Mauritius",
		"GlobalName":  "Mauritius",
		"TimeZone":    "Indian/Mauritius",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "YT",
		"ZoneName":    "Mayotte",
		"GlobalName":  "Mayotte",
		"TimeZone":    "Indian/Mayotte",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Bahia Banderas",
		"GlobalName":  "Bahia Banderas",
		"TimeZone":    "America/Bahia_Banderas",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Cancun",
		"GlobalName":  "Cancun",
		"TimeZone":    "America/Cancun",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Chihuahua",
		"GlobalName":  "Chihuahua",
		"TimeZone":    "America/Chihuahua",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Hermosillo",
		"GlobalName":  "Hermosillo",
		"TimeZone":    "America/Hermosillo",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Matamoros",
		"GlobalName":  "Matamoros",
		"TimeZone":    "America/Matamoros",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Mazatlan",
		"GlobalName":  "Mazatlan",
		"TimeZone":    "America/Mazatlan",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Merida",
		"GlobalName":  "Merida",
		"TimeZone":    "America/Merida",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Mexico City",
		"GlobalName":  "Mexico City",
		"TimeZone":    "America/Mexico_City",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Monterrey",
		"GlobalName":  "Monterrey",
		"TimeZone":    "America/Monterrey",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Ojinaga",
		"GlobalName":  "Ojinaga",
		"TimeZone":    "America/Ojinaga",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "MX",
		"ZoneName":    "Tijuana",
		"GlobalName":  "Tijuana",
		"TimeZone":    "America/Tijuana",
		"GtmOffset":   "UTC -08:00",
	},
	{
		"CountryCode": "FM",
		"ZoneName":    "Chuuk",
		"GlobalName":  "Chuuk",
		"TimeZone":    "Pacific/Chuuk",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "FM",
		"ZoneName":    "Kosrae",
		"GlobalName":  "Kosrae",
		"TimeZone":    "Pacific/Kosrae",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "FM",
		"ZoneName":    "Pohnpei",
		"GlobalName":  "Pohnpei",
		"TimeZone":    "Pacific/Pohnpei",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "MD",
		"ZoneName":    "Chisinau",
		"GlobalName":  "Chisinau",
		"TimeZone":    "Europe/Chisinau",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "MC",
		"ZoneName":    "Monaco",
		"GlobalName":  "Monaco",
		"TimeZone":    "Europe/Monaco",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "MN",
		"ZoneName":    "Choibalsan",
		"GlobalName":  "Choibalsan",
		"TimeZone":    "Asia/Choibalsan",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "MN",
		"ZoneName":    "Hovd",
		"GlobalName":  "Hovd",
		"TimeZone":    "Asia/Hovd",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "MN",
		"ZoneName":    "Ulaanbaatar",
		"GlobalName":  "Ulaanbaatar",
		"TimeZone":    "Asia/Ulaanbaatar",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "ME",
		"ZoneName":    "Podgorica",
		"GlobalName":  "Podgorica",
		"TimeZone":    "Europe/Podgorica",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "MS",
		"ZoneName":    "Montserrat",
		"GlobalName":  "Montserrat",
		"TimeZone":    "America/Montserrat",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "MA",
		"ZoneName":    "Casablanca",
		"GlobalName":  "Casablanca",
		"TimeZone":    "Africa/Casablanca",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "MZ",
		"ZoneName":    "Maputo",
		"GlobalName":  "Maputo",
		"TimeZone":    "Africa/Maputo",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "MM",
		"ZoneName":    "Yangon",
		"GlobalName":  "Yangon",
		"TimeZone":    "Asia/Yangon",
		"GtmOffset":   "UTC +06:30",
	},
	{
		"CountryCode": "NA",
		"ZoneName":    "Windhoek",
		"GlobalName":  "Windhoek",
		"TimeZone":    "Africa/Windhoek",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "NR",
		"ZoneName":    "Nauru",
		"GlobalName":  "Nauru",
		"TimeZone":    "Pacific/Nauru",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "NP",
		"ZoneName":    "Kathmandu",
		"GlobalName":  "Kathmandu",
		"TimeZone":    "Asia/Kathmandu",
		"GtmOffset":   "UTC +05:45",
	},
	{
		"CountryCode": "NL",
		"ZoneName":    "Amsterdam",
		"GlobalName":  "Amsterdam",
		"TimeZone":    "Europe/Amsterdam",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "NC",
		"ZoneName":    "Noumea",
		"GlobalName":  "Noumea",
		"TimeZone":    "Pacific/Noumea",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "NZ",
		"ZoneName":    "Auckland",
		"GlobalName":  "Auckland",
		"TimeZone":    "Pacific/Auckland",
		"GtmOffset":   "UTC +13:00",
	},
	{
		"CountryCode": "NZ",
		"ZoneName":    "Chatham",
		"GlobalName":  "Chatham",
		"TimeZone":    "Pacific/Chatham",
		"GtmOffset":   "UTC +13:45",
	},
	{
		"CountryCode": "NI",
		"ZoneName":    "Managua",
		"GlobalName":  "Managua",
		"TimeZone":    "America/Managua",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "NE",
		"ZoneName":    "Niamey",
		"GlobalName":  "Niamey",
		"TimeZone":    "Africa/Niamey",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "NG",
		"ZoneName":    "Lagos",
		"GlobalName":  "Lagos",
		"TimeZone":    "Africa/Lagos",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "NU",
		"ZoneName":    "Niue",
		"GlobalName":  "Niue",
		"TimeZone":    "Pacific/Niue",
		"GtmOffset":   "UTC -11:00",
	},
	{
		"CountryCode": "NF",
		"ZoneName":    "Norfolk",
		"GlobalName":  "Norfolk",
		"TimeZone":    "Pacific/Norfolk",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "MP",
		"ZoneName":    "Saipan",
		"GlobalName":  "Saipan",
		"TimeZone":    "Pacific/Saipan",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "NO",
		"ZoneName":    "Oslo",
		"GlobalName":  "Oslo",
		"TimeZone":    "Europe/Oslo",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "OM",
		"ZoneName":    "Muscat",
		"GlobalName":  "Muscat",
		"TimeZone":    "Asia/Muscat",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "PK",
		"ZoneName":    "Karachi",
		"GlobalName":  "Karachi",
		"TimeZone":    "Asia/Karachi",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "PW",
		"ZoneName":    "Palau",
		"GlobalName":  "Palau",
		"TimeZone":    "Pacific/Palau",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "PS",
		"ZoneName":    "Gaza",
		"GlobalName":  "Gaza",
		"TimeZone":    "Asia/Gaza",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "PS",
		"ZoneName":    "Hebron",
		"GlobalName":  "Hebron",
		"TimeZone":    "Asia/Hebron",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "PA",
		"ZoneName":    "Panama",
		"GlobalName":  "Panama",
		"TimeZone":    "America/Panama",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "PG",
		"ZoneName":    "Bougainville",
		"GlobalName":  "Bougainville",
		"TimeZone":    "Pacific/Bougainville",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "PG",
		"ZoneName":    "Port Moresby",
		"GlobalName":  "Port Moresby",
		"TimeZone":    "Pacific/Port_Moresby",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "PY",
		"ZoneName":    "Asuncion",
		"GlobalName":  "Asuncion",
		"TimeZone":    "America/Asuncion",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "PE",
		"ZoneName":    "Lima",
		"GlobalName":  "Lima",
		"TimeZone":    "America/Lima",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "PH",
		"ZoneName":    "Manila",
		"GlobalName":  "Manila",
		"TimeZone":    "Asia/Manila",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "PN",
		"ZoneName":    "Pitcairn",
		"GlobalName":  "Pitcairn",
		"TimeZone":    "Pacific/Pitcairn",
		"GtmOffset":   "UTC -08:00",
	},
	{
		"CountryCode": "PL",
		"ZoneName":    "Warsaw",
		"GlobalName":  "Warsaw",
		"TimeZone":    "Europe/Warsaw",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "PT",
		"ZoneName":    "Azores",
		"GlobalName":  "Azores",
		"TimeZone":    "Atlantic/Azores",
		"GtmOffset":   "UTC -01:00",
	},
	{
		"CountryCode": "PT",
		"ZoneName":    "Madeira",
		"GlobalName":  "Madeira",
		"TimeZone":    "Atlantic/Madeira",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "PT",
		"ZoneName":    "Lisbon",
		"GlobalName":  "Lisbon",
		"TimeZone":    "Europe/Lisbon",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "PR",
		"ZoneName":    "Puerto Rico",
		"GlobalName":  "Puerto Rico",
		"TimeZone":    "America/Puerto_Rico",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "QA",
		"ZoneName":    "Qatar",
		"GlobalName":  "Qatar",
		"TimeZone":    "Asia/Qatar",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "RO",
		"ZoneName":    "Bucharest",
		"GlobalName":  "Bucharest",
		"TimeZone":    "Europe/Bucharest",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Anadyr",
		"GlobalName":  "Anadyr",
		"TimeZone":    "Asia/Anadyr",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Barnaul",
		"GlobalName":  "Barnaul",
		"TimeZone":    "Asia/Barnaul",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Chita",
		"GlobalName":  "Chita",
		"TimeZone":    "Asia/Chita",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Irkutsk",
		"GlobalName":  "Irkutsk",
		"TimeZone":    "Asia/Irkutsk",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Kamchatka",
		"GlobalName":  "Kamchatka",
		"TimeZone":    "Asia/Kamchatka",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Khandyga",
		"GlobalName":  "Khandyga",
		"TimeZone":    "Asia/Khandyga",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Krasnoyarsk",
		"GlobalName":  "Krasnoyarsk",
		"TimeZone":    "Asia/Krasnoyarsk",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Magadan",
		"GlobalName":  "Magadan",
		"TimeZone":    "Asia/Magadan",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Novokuznetsk",
		"GlobalName":  "Novokuznetsk",
		"TimeZone":    "Asia/Novokuznetsk",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Novosibirsk",
		"GlobalName":  "Novosibirsk",
		"TimeZone":    "Asia/Novosibirsk",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Omsk",
		"GlobalName":  "Omsk",
		"TimeZone":    "Asia/Omsk",
		"GtmOffset":   "UTC +06:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Sakhalin",
		"GlobalName":  "Sakhalin",
		"TimeZone":    "Asia/Sakhalin",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Srednekolymsk",
		"GlobalName":  "Srednekolymsk",
		"TimeZone":    "Asia/Srednekolymsk",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Tomsk",
		"GlobalName":  "Tomsk",
		"TimeZone":    "Asia/Tomsk",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Ust-Nera",
		"GlobalName":  "Ust-Nera",
		"TimeZone":    "Asia/Ust-Nera",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Vladivostok",
		"GlobalName":  "Vladivostok",
		"TimeZone":    "Asia/Vladivostok",
		"GtmOffset":   "UTC +10:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Yakutsk",
		"GlobalName":  "Yakutsk",
		"TimeZone":    "Asia/Yakutsk",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Yekaterinburg",
		"GlobalName":  "Yekaterinburg",
		"TimeZone":    "Asia/Yekaterinburg",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Astrakhan",
		"GlobalName":  "Astrakhan",
		"TimeZone":    "Europe/Astrakhan",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Kaliningrad",
		"GlobalName":  "Kaliningrad",
		"TimeZone":    "Europe/Kaliningrad",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Kirov",
		"GlobalName":  "Kirov",
		"TimeZone":    "Europe/Kirov",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Moscow",
		"GlobalName":  "Moscow",
		"TimeZone":    "Europe/Moscow",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Samara",
		"GlobalName":  "Samara",
		"TimeZone":    "Europe/Samara",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Saratov",
		"GlobalName":  "Saratov",
		"TimeZone":    "Europe/Saratov",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Ulyanovsk",
		"GlobalName":  "Ulyanovsk",
		"TimeZone":    "Europe/Ulyanovsk",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "RU",
		"ZoneName":    "Volgograd",
		"GlobalName":  "Volgograd",
		"TimeZone":    "Europe/Volgograd",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "RW",
		"ZoneName":    "Kigali",
		"GlobalName":  "Kigali",
		"TimeZone":    "Africa/Kigali",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "RE",
		"ZoneName":    "Reunion",
		"GlobalName":  "Reunion",
		"TimeZone":    "Indian/Reunion",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "BL",
		"ZoneName":    "St Barthelemy",
		"GlobalName":  "St Barthelemy",
		"TimeZone":    "America/St_Barthelemy",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "SH",
		"ZoneName":    "St Helena",
		"GlobalName":  "St Helena",
		"TimeZone":    "Atlantic/St_Helena",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "KN",
		"ZoneName":    "St Kitts",
		"GlobalName":  "St Kitts",
		"TimeZone":    "America/St_Kitts",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "LC",
		"ZoneName":    "St Lucia",
		"GlobalName":  "St Lucia",
		"TimeZone":    "America/St_Lucia",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "MF",
		"ZoneName":    "Marigot",
		"GlobalName":  "Marigot",
		"TimeZone":    "America/Marigot",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "PM",
		"ZoneName":    "Miquelon",
		"GlobalName":  "Miquelon",
		"TimeZone":    "America/Miquelon",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "VC",
		"ZoneName":    "St Vincent",
		"GlobalName":  "St Vincent",
		"TimeZone":    "America/St_Vincent",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "WS",
		"ZoneName":    "Apia",
		"GlobalName":  "Apia",
		"TimeZone":    "Pacific/Apia",
		"GtmOffset":   "UTC +14:00",
	},
	{
		"CountryCode": "SM",
		"ZoneName":    "San Marino",
		"GlobalName":  "San Marino",
		"TimeZone":    "Europe/San_Marino",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "ST",
		"ZoneName":    "Sao Tome",
		"GlobalName":  "Sao Tome",
		"TimeZone":    "Africa/Sao_Tome",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "SA",
		"ZoneName":    "Riyadh",
		"GlobalName":  "Riyadh",
		"TimeZone":    "Asia/Riyadh",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "SN",
		"ZoneName":    "Dakar",
		"GlobalName":  "Dakar",
		"TimeZone":    "Africa/Dakar",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "RS",
		"ZoneName":    "Belgrade",
		"GlobalName":  "Belgrade",
		"TimeZone":    "Europe/Belgrade",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "SC",
		"ZoneName":    "Mahe",
		"GlobalName":  "Mahe",
		"TimeZone":    "Indian/Mahe",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "SL",
		"ZoneName":    "Freetown",
		"GlobalName":  "Freetown",
		"TimeZone":    "Africa/Freetown",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "SG",
		"ZoneName":    "Singapore",
		"GlobalName":  "Singapore",
		"TimeZone":    "Asia/Singapore",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "SX",
		"ZoneName":    "Lower Princes",
		"GlobalName":  "Lower Princes",
		"TimeZone":    "America/Lower_Princes",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "SK",
		"ZoneName":    "Bratislava",
		"GlobalName":  "Bratislava",
		"TimeZone":    "Europe/Bratislava",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "SI",
		"ZoneName":    "Ljubljana",
		"GlobalName":  "Ljubljana",
		"TimeZone":    "Europe/Ljubljana",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "SB",
		"ZoneName":    "Guadalcanal",
		"GlobalName":  "Guadalcanal",
		"TimeZone":    "Pacific/Guadalcanal",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "SO",
		"ZoneName":    "Mogadishu",
		"GlobalName":  "Mogadishu",
		"TimeZone":    "Africa/Mogadishu",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "ZA",
		"ZoneName":    "Johannesburg",
		"GlobalName":  "Johannesburg",
		"TimeZone":    "Africa/Johannesburg",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "GS",
		"ZoneName":    "South Georgia",
		"GlobalName":  "South Georgia",
		"TimeZone":    "Atlantic/South_Georgia",
		"GtmOffset":   "UTC -02:00",
	},
	{
		"CountryCode": "SS",
		"ZoneName":    "Juba",
		"GlobalName":  "Juba",
		"TimeZone":    "Africa/Juba",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "ES",
		"ZoneName":    "Ceuta",
		"GlobalName":  "Ceuta",
		"TimeZone":    "Africa/Ceuta",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "ES",
		"ZoneName":    "Canary",
		"GlobalName":  "Canary",
		"TimeZone":    "Atlantic/Canary",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "ES",
		"ZoneName":    "Madrid",
		"GlobalName":  "Madrid",
		"TimeZone":    "Europe/Madrid",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "LK",
		"ZoneName":    "Colombo",
		"GlobalName":  "Colombo",
		"TimeZone":    "Asia/Colombo",
		"GtmOffset":   "UTC +05:30",
	},
	{
		"CountryCode": "SD",
		"ZoneName":    "Khartoum",
		"GlobalName":  "Khartoum",
		"TimeZone":    "Africa/Khartoum",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "SR",
		"ZoneName":    "Paramaribo",
		"GlobalName":  "Paramaribo",
		"TimeZone":    "America/Paramaribo",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "SJ",
		"ZoneName":    "Longyearbyen",
		"GlobalName":  "Longyearbyen",
		"TimeZone":    "Arctic/Longyearbyen",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "SZ",
		"ZoneName":    "Mbabane",
		"GlobalName":  "Mbabane",
		"TimeZone":    "Africa/Mbabane",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "SE",
		"ZoneName":    "Stockholm",
		"GlobalName":  "Stockholm",
		"TimeZone":    "Europe/Stockholm",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "CH",
		"ZoneName":    "Zurich",
		"GlobalName":  "Zurich",
		"TimeZone":    "Europe/Zurich",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "SY",
		"ZoneName":    "Damascus",
		"GlobalName":  "Damascus",
		"TimeZone":    "Asia/Damascus",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "TW",
		"ZoneName":    "Taipei",
		"GlobalName":  "Taipei",
		"TimeZone":    "Asia/Taipei",
		"GtmOffset":   "UTC +08:00",
	},
	{
		"CountryCode": "TJ",
		"ZoneName":    "Dushanbe",
		"GlobalName":  "Dushanbe",
		"TimeZone":    "Asia/Dushanbe",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "TZ",
		"ZoneName":    "Dar es_Salaam",
		"GlobalName":  "Dar es_Salaam",
		"TimeZone":    "Africa/Dar_es_Salaam",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "TH",
		"ZoneName":    "Bangkok",
		"GlobalName":  "Bangkok",
		"TimeZone":    "Asia/Bangkok",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "TL",
		"ZoneName":    "Dili",
		"GlobalName":  "Dili",
		"TimeZone":    "Asia/Dili",
		"GtmOffset":   "UTC +09:00",
	},
	{
		"CountryCode": "TG",
		"ZoneName":    "Lome",
		"GlobalName":  "Lome",
		"TimeZone":    "Africa/Lome",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "TK",
		"ZoneName":    "Fakaofo",
		"GlobalName":  "Fakaofo",
		"TimeZone":    "Pacific/Fakaofo",
		"GtmOffset":   "UTC +13:00",
	},
	{
		"CountryCode": "TO",
		"ZoneName":    "Tongatapu",
		"GlobalName":  "Tongatapu",
		"TimeZone":    "Pacific/Tongatapu",
		"GtmOffset":   "UTC +13:00",
	},
	{
		"CountryCode": "TT",
		"ZoneName":    "Port of_Spain",
		"GlobalName":  "Port of_Spain",
		"TimeZone":    "America/Port_of_Spain",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "TN",
		"ZoneName":    "Tunis",
		"GlobalName":  "Tunis",
		"TimeZone":    "Africa/Tunis",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "TR",
		"ZoneName":    "Istanbul",
		"GlobalName":  "Istanbul",
		"TimeZone":    "Europe/Istanbul",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "TM",
		"ZoneName":    "Ashgabat",
		"GlobalName":  "Ashgabat",
		"TimeZone":    "Asia/Ashgabat",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "TC",
		"ZoneName":    "Grand Turk",
		"GlobalName":  "Grand Turk",
		"TimeZone":    "America/Grand_Turk",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "TV",
		"ZoneName":    "Funafuti",
		"GlobalName":  "Funafuti",
		"TimeZone":    "Pacific/Funafuti",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "UG",
		"ZoneName":    "Kampala",
		"GlobalName":  "Kampala",
		"TimeZone":    "Africa/Kampala",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "UA",
		"ZoneName":    "Kiev",
		"GlobalName":  "Kiev",
		"TimeZone":    "Europe/Kiev",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "UA",
		"ZoneName":    "Simferopol",
		"GlobalName":  "Simferopol",
		"TimeZone":    "Europe/Simferopol",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "UA",
		"ZoneName":    "Uzhgorod",
		"GlobalName":  "Uzhgorod",
		"TimeZone":    "Europe/Uzhgorod",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "UA",
		"ZoneName":    "Zaporozhye",
		"GlobalName":  "Zaporozhye",
		"TimeZone":    "Europe/Zaporozhye",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "AE",
		"ZoneName":    "Dubai",
		"GlobalName":  "Dubai",
		"TimeZone":    "Asia/Dubai",
		"GtmOffset":   "UTC +04:00",
	},
	{
		"CountryCode": "GB",
		"ZoneName":    "London",
		"GlobalName":  "London",
		"TimeZone":    "Europe/London",
		"GtmOffset":   "UTC",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Adak",
		"GlobalName":  "Adak",
		"TimeZone":    "America/Adak",
		"GtmOffset":   "UTC -10:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Anchorage",
		"GlobalName":  "Anchorage",
		"TimeZone":    "America/Anchorage",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Boise",
		"GlobalName":  "Boise",
		"TimeZone":    "America/Boise",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Chicago",
		"GlobalName":  "Chicago",
		"TimeZone":    "America/Chicago",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Denver",
		"GlobalName":  "Denver",
		"TimeZone":    "America/Denver",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Detroit",
		"GlobalName":  "Detroit",
		"TimeZone":    "America/Detroit",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Indianapolis",
		"GlobalName":  "Indianapolis",
		"TimeZone":    "America/Indiana/Indianapolis",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Knox",
		"GlobalName":  "Knox",
		"TimeZone":    "America/Indiana/Knox",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Marengo",
		"GlobalName":  "Marengo",
		"TimeZone":    "America/Indiana/Marengo",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Petersburg",
		"GlobalName":  "Petersburg",
		"TimeZone":    "America/Indiana/Petersburg",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Tell City",
		"GlobalName":  "Tell City",
		"TimeZone":    "America/Indiana/Tell_City",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Vevay",
		"GlobalName":  "Vevay",
		"TimeZone":    "America/Indiana/Vevay",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Vincennes",
		"GlobalName":  "Vincennes",
		"TimeZone":    "America/Indiana/Vincennes",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Winamac",
		"GlobalName":  "Winamac",
		"TimeZone":    "America/Indiana/Winamac",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Juneau",
		"GlobalName":  "Juneau",
		"TimeZone":    "America/Juneau",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Louisville",
		"GlobalName":  "Louisville",
		"TimeZone":    "America/Kentucky/Louisville",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Monticello",
		"GlobalName":  "Monticello",
		"TimeZone":    "America/Kentucky/Monticello",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Los Angeles",
		"GlobalName":  "Los Angeles",
		"TimeZone":    "America/Los_Angeles",
		"GtmOffset":   "UTC -08:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Menominee",
		"GlobalName":  "Menominee",
		"TimeZone":    "America/Menominee",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Metlakatla",
		"GlobalName":  "Metlakatla",
		"TimeZone":    "America/Metlakatla",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "New York",
		"GlobalName":  "New York",
		"TimeZone":    "America/New_York",
		"GtmOffset":   "UTC -05:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Nome",
		"GlobalName":  "Nome",
		"TimeZone":    "America/Nome",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Beulah",
		"GlobalName":  "Beulah",
		"TimeZone":    "America/North_Dakota/Beulah",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Center",
		"GlobalName":  "Center",
		"TimeZone":    "America/North_Dakota/Center",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "New Salem",
		"GlobalName":  "New Salem",
		"TimeZone":    "America/North_Dakota/New_Salem",
		"GtmOffset":   "UTC -06:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Phoenix",
		"GlobalName":  "Phoenix",
		"TimeZone":    "America/Phoenix",
		"GtmOffset":   "UTC -07:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Sitka",
		"GlobalName":  "Sitka",
		"TimeZone":    "America/Sitka",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Yakutat",
		"GlobalName":  "Yakutat",
		"TimeZone":    "America/Yakutat",
		"GtmOffset":   "UTC -09:00",
	},
	{
		"CountryCode": "US",
		"ZoneName":    "Honolulu",
		"GlobalName":  "Honolulu",
		"TimeZone":    "Pacific/Honolulu",
		"GtmOffset":   "UTC -10:00",
	},
	{
		"CountryCode": "UM",
		"ZoneName":    "Midway",
		"GlobalName":  "Midway",
		"TimeZone":    "Pacific/Midway",
		"GtmOffset":   "UTC -11:00",
	},
	{
		"CountryCode": "UM",
		"ZoneName":    "Wake",
		"GlobalName":  "Wake",
		"TimeZone":    "Pacific/Wake",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "UY",
		"ZoneName":    "Montevideo",
		"GlobalName":  "Montevideo",
		"TimeZone":    "America/Montevideo",
		"GtmOffset":   "UTC -03:00",
	},
	{
		"CountryCode": "UZ",
		"ZoneName":    "Samarkand",
		"GlobalName":  "Samarkand",
		"TimeZone":    "Asia/Samarkand",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "UZ",
		"ZoneName":    "Tashkent",
		"GlobalName":  "Tashkent",
		"TimeZone":    "Asia/Tashkent",
		"GtmOffset":   "UTC +05:00",
	},
	{
		"CountryCode": "VU",
		"ZoneName":    "Efate",
		"GlobalName":  "Efate",
		"TimeZone":    "Pacific/Efate",
		"GtmOffset":   "UTC +11:00",
	},
	{
		"CountryCode": "VE",
		"ZoneName":    "Caracas",
		"GlobalName":  "Caracas",
		"TimeZone":    "America/Caracas",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "VN",
		"ZoneName":    "Ho Chi_Minh",
		"GlobalName":  "Ho Chi_Minh",
		"TimeZone":    "Asia/Ho_Chi_Minh",
		"GtmOffset":   "UTC +07:00",
	},
	{
		"CountryCode": "VG",
		"ZoneName":    "Tortola",
		"GlobalName":  "Tortola",
		"TimeZone":    "America/Tortola",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "VI",
		"ZoneName":    "St Thomas",
		"GlobalName":  "St Thomas",
		"TimeZone":    "America/St_Thomas",
		"GtmOffset":   "UTC -04:00",
	},
	{
		"CountryCode": "WF",
		"ZoneName":    "Wallis",
		"GlobalName":  "Wallis",
		"TimeZone":    "Pacific/Wallis",
		"GtmOffset":   "UTC +12:00",
	},
	{
		"CountryCode": "EH",
		"ZoneName":    "El Aaiun",
		"GlobalName":  "El Aaiun",
		"TimeZone":    "Africa/El_Aaiun",
		"GtmOffset":   "UTC +01:00",
	},
	{
		"CountryCode": "YE",
		"ZoneName":    "Aden",
		"GlobalName":  "Aden",
		"TimeZone":    "Asia/Aden",
		"GtmOffset":   "UTC +03:00",
	},
	{
		"CountryCode": "ZM",
		"ZoneName":    "Lusaka",
		"GlobalName":  "Lusaka",
		"TimeZone":    "Africa/Lusaka",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "ZW",
		"ZoneName":    "Harare",
		"GlobalName":  "Harare",
		"TimeZone":    "Africa/Harare",
		"GtmOffset":   "UTC +02:00",
	},
	{
		"CountryCode": "AX",
		"ZoneName":    "Mariehamn",
		"GlobalName":  "Mariehamn",
		"TimeZone":    "Europe/Mariehamn",
		"GtmOffset":   "UTC +02:00",
	},
}

func (store *Store) seedTimezonesIfTableEmpty() error {
	list, err := store.TimezoneList(TimezoneQueryOptions{
		Limit: 1,
	})

	if err != nil {
		return err
	}

	if len(list) > 0 {
		return nil
	}

	for _, entry := range timezones {
		timezone := NewTimezone()
		timezone.SetTimezone(entry["TimeZone"])
		timezone.SetCountryCode(entry["CountryCode"])
		timezone.SetZoneName(entry["ZoneName"])
		timezone.SetGlobalName(entry["GlobalName"])
		timezone.SetOffset(entry["GtmOffset"])

		err = store.TimezoneCreate(timezone)

		if err != nil {
			return err
		}
	}

	return nil
}
