package geostore

var countries = []map[string]string{

	{
		"Iso2":      "AC",
		"Iso3":      "ASC",
		"Name":      "Ascension Island",
		"Continent": "eu",
		"Prefix":    "247",
	},
	{
		"Iso2":      "AD",
		"Iso3":      "AND",
		"Name":      "Andorra",
		"Continent": "eu",
		"Prefix":    "376",
	},
	{
		"Iso2":      "AE",
		"Iso3":      "ARE",
		"Name":      "United Arab Emirates",
		"Continent": "as",
		"Prefix":    "971",
	},
	{
		"Iso2":      "AF",
		"Iso3":      "AFG",
		"Name":      "Afghanistan",
		"Continent": "as",
		"Prefix":    "93",
	},
	{
		"Iso2":      "AG",
		"Iso3":      "ATG",
		"Name":      "Antigua and Barbuda",
		"Continent": "na",
		"Prefix":    "1268",
	},
	{
		"Iso2":      "AI",
		"Iso3":      "AIA",
		"Name":      "Anguilla",
		"Continent": "na",
		"Prefix":    "1264",
	},
	{
		"Iso2":      "AL",
		"Iso3":      "ALB",
		"Name":      "Albania",
		"Continent": "eu",
		"Prefix":    "355",
	},
	{
		"Iso2":      "AM",
		"Iso3":      "ARM",
		"Name":      "Armenia",
		"Continent": "am",
		"Prefix":    "374",
	},
	{
		"Iso2":      "AN",
		"Iso3":      "ANT",
		"Name":      "Netherlands Antilles",
		"Continent": "sa",
		"Prefix":    "599",
	},
	{
		"Iso2":      "AO",
		"Iso3":      "AGO",
		"Name":      "Angola",
		"Continent": "af",
		"Prefix":    "244",
	},
	{
		"Iso2":      "AQ",
		"Iso3":      "ATA",
		"Name":      "Antarctica",
		"Continent": "an",
		"Prefix":    "672",
	},
	{
		"Iso2":      "AR",
		"Iso3":      "ARG",
		"Name":      "Argentina",
		"Continent": "sa",
		"Prefix":    "54",
	},
	{
		"Iso2":      "AS",
		"Iso3":      "ASM",
		"Name":      "American Samoa",
		"Continent": "oc",
		"Prefix":    "684",
	},
	{
		"Iso2":      "AT",
		"Iso3":      "AUT",
		"Name":      "Austria",
		"Continent": "eu",
		"Prefix":    "43",
	},
	{
		"Iso2":      "AU",
		"Iso3":      "AUS",
		"Name":      "Australia",
		"Continent": "oc",
		"Prefix":    "61",
	},
	{
		"Iso2":      "AW",
		"Iso3":      "ABW",
		"Name":      "Aruba",
		"Continent": "na",
		"Prefix":    "297",
	},
	{
		"Iso2":      "AX",
		"Iso3":      "ALA",
		"Name":      "Aland Islands",
		"Continent": "eu",
		"Prefix":    "358",
	},
	{
		"Iso2":      "AZ",
		"Iso3":      "AZE",
		"Name":      "Azerbaijan",
		"Continent": "az",
		"Prefix":    "994",
	},
	{
		"Iso2":      "BA",
		"Iso3":      "BIH",
		"Name":      "Bosnia and Herzegovina",
		"Continent": "eu",
		"Prefix":    "387",
	},
	{
		"Iso2":      "BB",
		"Iso3":      "BRB",
		"Name":      "Barbados",
		"Continent": "na",
		"Prefix":    "1246",
	},
	{
		"Iso2":      "BD",
		"Iso3":      "BGD",
		"Name":      "Bangladesh",
		"Continent": "as",
		"Prefix":    "880",
	},
	{
		"Iso2":      "BE",
		"Iso3":      "BEL",
		"Name":      "Belgium",
		"Continent": "eu",
		"Prefix":    "32",
	},
	{
		"Iso2":      "BF",
		"Iso3":      "BFA",
		"Name":      "Burkina Faso",
		"Continent": "af",
		"Prefix":    "226",
	},
	{
		"Iso2":      "BG",
		"Iso3":      "BGR",
		"Name":      "Bulgaria",
		"Continent": "eu",
		"Prefix":    "359",
	},
	{
		"Iso2":      "BH",
		"Iso3":      "BHR",
		"Name":      "Bahrain",
		"Continent": "as",
		"Prefix":    "973",
	},
	{
		"Iso2":      "BI",
		"Iso3":      "BDI",
		"Name":      "Burundi",
		"Continent": "af",
		"Prefix":    "257",
	},
	{
		"Iso2":      "BJ",
		"Iso3":      "BEN",
		"Name":      "Benin",
		"Continent": "af",
		"Prefix":    "229",
	},
	{
		"Iso2":      "BM",
		"Iso3":      "BMU",
		"Name":      "Bermuda",
		"Continent": "na",
		"Prefix":    "1441",
	},
	{
		"Iso2":      "BN",
		"Iso3":      "BRN",
		"Name":      "Brunei Darussalam",
		"Continent": "as",
		"Prefix":    "673",
	},
	{
		"Iso2":      "BO",
		"Iso3":      "BOL",
		"Name":      "Bolivia",
		"Continent": "sa",
		"Prefix":    "591",
	},
	{
		"Iso2":      "BR",
		"Iso3":      "BRA",
		"Name":      "Brazil",
		"Continent": "sa",
		"Prefix":    "55",
	},
	{
		"Iso2":      "BS",
		"Iso3":      "BHS",
		"Name":      "Bahamas",
		"Continent": "na",
		"Prefix":    "1242",
	},
	{
		"Iso2":      "BT",
		"Iso3":      "BTN",
		"Name":      "Bhutan",
		"Continent": "as",
		"Prefix":    "975",
	},
	{
		"Iso2":      "BV",
		"Iso3":      "BVT",
		"Name":      "Bouvet Island",
		"Continent": "an",
		"Prefix":    "47",
	},
	{
		"Iso2":      "BW",
		"Iso3":      "BWA",
		"Name":      "Botswana",
		"Continent": "af",
		"Prefix":    "267",
	},
	{
		"Iso2":      "BY",
		"Iso3":      "BLR",
		"Name":      "Belarus",
		"Continent": "eu",
		"Prefix":    "375",
	},
	{
		"Iso2":      "BZ",
		"Iso3":      "BLZ",
		"Name":      "Belize",
		"Continent": "na",
		"Prefix":    "501",
	},
	{
		"Iso2":      "CA",
		"Iso3":      "CAN",
		"Name":      "Canada",
		"Continent": "na",
		"Prefix":    "1",
	},
	{
		"Iso2":      "CC",
		"Iso3":      "CCK",
		"Name":      "Cocos (Keeling) Islands",
		"Continent": "as",
		"Prefix":    "891",
	},
	{
		"Iso2":      "CD",
		"Iso3":      "COD",
		"Name":      "Congo, the Democratic Republic of the",
		"Continent": "af",
		"Prefix":    "243",
	},
	{
		"Iso2":      "CF",
		"Iso3":      "CAF",
		"Name":      "Central African Republic",
		"Continent": "af",
		"Prefix":    "236",
	},
	{
		"Iso2":      "CG",
		"Iso3":      "COG",
		"Name":      "Congo",
		"Continent": "af",
		"Prefix":    "242",
	},
	{
		"Iso2":      "CH",
		"Iso3":      "CHE",
		"Name":      "Switzerland",
		"Continent": "eu",
		"Prefix":    "41",
	},
	{
		"Iso2":      "CI",
		"Iso3":      "CIV",
		"Name":      "Cote D'Ivoire",
		"Continent": "af",
		"Prefix":    "225",
	},
	{
		"Iso2":      "CK",
		"Iso3":      "COK",
		"Name":      "Cook Islands",
		"Continent": "oc",
		"Prefix":    "682",
	},
	{
		"Iso2":      "CL",
		"Iso3":      "CHL",
		"Name":      "Chile",
		"Continent": "sa",
		"Prefix":    "56",
	},
	{
		"Iso2":      "CM",
		"Iso3":      "CMR",
		"Name":      "Cameroon",
		"Continent": "af",
		"Prefix":    "237",
	},
	{
		"Iso2":      "CN",
		"Iso3":      "CHN",
		"Name":      "China",
		"Continent": "as",
		"Prefix":    "86",
	},
	{
		"Iso2":      "CO",
		"Iso3":      "COL",
		"Name":      "Colombia",
		"Continent": "sa",
		"Prefix":    "57",
	},
	{
		"Iso2":      "CR",
		"Iso3":      "CRI",
		"Name":      "Costa Rica",
		"Continent": "na",
		"Prefix":    "506",
	},
	{
		"Iso2":      "CU",
		"Iso3":      "CUB",
		"Name":      "Cuba",
		"Continent": "na",
		"Prefix":    "53",
	},
	{
		"Iso2":      "CV",
		"Iso3":      "CPV",
		"Name":      "Cape Verde",
		"Continent": "af",
		"Prefix":    "238",
	},
	{
		"Iso2":      "CX",
		"Iso3":      "CXR",
		"Name":      "Christmas Island",
		"Continent": "as",
		"Prefix":    "61",
	},
	{
		"Iso2":      "CY",
		"Iso3":      "CYP",
		"Name":      "Cyprus",
		"Continent": "as",
		"Prefix":    "357",
	},
	{
		"Iso2":      "CZ",
		"Iso3":      "CZE",
		"Name":      "Czech Republic",
		"Continent": "eu",
		"Prefix":    "420",
	},
	{
		"Iso2":      "DE",
		"Iso3":      "DEU",
		"Name":      "Germany",
		"Continent": "eu",
		"Prefix":    "49",
	},
	{
		"Iso2":      "DJ",
		"Iso3":      "DJI",
		"Name":      "Djibouti",
		"Continent": "af",
		"Prefix":    "253",
	},
	{
		"Iso2":      "DK",
		"Iso3":      "DNK",
		"Name":      "Denmark",
		"Continent": "eu",
		"Prefix":    "45",
	},
	{
		"Iso2":      "DM",
		"Iso3":      "DMA",
		"Name":      "Dominica",
		"Continent": "na",
		"Prefix":    "1767",
	},
	{
		"Iso2":      "DO",
		"Iso3":      "DOM",
		"Name":      "Dominican Republic",
		"Continent": "na",
		"Prefix":    "1809",
	},
	{
		"Iso2":      "DZ",
		"Iso3":      "DZA",
		"Name":      "Algeria",
		"Continent": "af",
		"Prefix":    "213",
	},
	{
		"Iso2":      "EC",
		"Iso3":      "ECU",
		"Name":      "Ecuador",
		"Continent": "sa",
		"Prefix":    "593",
	},
	{
		"Iso2":      "EE",
		"Iso3":      "EST",
		"Name":      "Estonia",
		"Continent": "eu",
		"Prefix":    "372",
	},
	{
		"Iso2":      "EG",
		"Iso3":      "EGY",
		"Name":      "Egypt",
		"Continent": "af",
		"Prefix":    "20",
	},
	{
		"Iso2":      "EH",
		"Iso3":      "ESH",
		"Name":      "Western Sahara",
		"Continent": "af",
		"Prefix":    "212",
	},
	{
		"Iso2":      "ER",
		"Iso3":      "ERI",
		"Name":      "Eritrea",
		"Continent": "af",
		"Prefix":    "291",
	},
	{
		"Iso2":      "ES",
		"Iso3":      "ESP",
		"Name":      "Spain",
		"Continent": "eu",
		"Prefix":    "34",
	},
	{
		"Iso2":      "ET",
		"Iso3":      "ETH",
		"Name":      "Ethiopia",
		"Continent": "af",
		"Prefix":    "251",
	},
	{
		"Iso2":      "FI",
		"Iso3":      "FIN",
		"Name":      "Finland",
		"Continent": "eu",
		"Prefix":    "358",
	},
	{
		"Iso2":      "FJ",
		"Iso3":      "FJI",
		"Name":      "Fiji",
		"Continent": "oc",
		"Prefix":    "679",
	},
	{
		"Iso2":      "FK",
		"Iso3":      "FLK",
		"Name":      "Falkland Islands (Malvinas)",
		"Continent": "sa",
		"Prefix":    "500",
	},
	{
		"Iso2":      "FM",
		"Iso3":      "FSM",
		"Name":      "Micronesia, Federated States of",
		"Continent": "oc",
		"Prefix":    "691",
	},
	{
		"Iso2":      "FO",
		"Iso3":      "FRO",
		"Name":      "Faroe Islands",
		"Continent": "eu",
		"Prefix":    "298",
	},
	{
		"Iso2":      "FR",
		"Iso3":      "FRA",
		"Name":      "France",
		"Continent": "eu",
		"Prefix":    "33",
	},
	{
		"Iso2":      "GA",
		"Iso3":      "GAB",
		"Name":      "Gabon",
		"Continent": "af",
		"Prefix":    "241",
	},
	{
		"Iso2":      "GB",
		"Iso3":      "GBR",
		"Name":      "United Kingdom",
		"Continent": "eu",
		"Prefix":    "44",
	},
	{
		"Iso2":      "GD",
		"Iso3":      "GRD",
		"Name":      "Grenada",
		"Continent": "na",
		"Prefix":    "1473",
	},
	{
		"Iso2":      "GE",
		"Iso3":      "GEO",
		"Name":      "Georgia",
		"Continent": "as",
		"Prefix":    "995",
	},
	{
		"Iso2":      "GF",
		"Iso3":      "GUF",
		"Name":      "French Guiana",
		"Continent": "sa",
		"Prefix":    "594",
	},
	{
		"Iso2":      "GH",
		"Iso3":      "GHA",
		"Name":      "Ghana",
		"Continent": "af",
		"Prefix":    "233",
	},
	{
		"Iso2":      "GI",
		"Iso3":      "GIB",
		"Name":      "Gibraltar",
		"Continent": "eu",
		"Prefix":    "350",
	},
	{
		"Iso2":      "GL",
		"Iso3":      "GRL",
		"Name":      "Greenland",
		"Continent": "na",
		"Prefix":    "299",
	},
	{
		"Iso2":      "GM",
		"Iso3":      "GMB",
		"Name":      "Gambia",
		"Continent": "af",
		"Prefix":    "220",
	},
	{
		"Iso2":      "GN",
		"Iso3":      "GIN",
		"Name":      "Guinea",
		"Continent": "af",
		"Prefix":    "224",
	},
	{
		"Iso2":      "GP",
		"Iso3":      "GLP",
		"Name":      "Guadeloupe",
		"Continent": "na",
		"Prefix":    "590",
	},
	{
		"Iso2":      "GQ",
		"Iso3":      "GNQ",
		"Name":      "Equatorial Guinea",
		"Continent": "af",
		"Prefix":    "240",
	},
	{
		"Iso2":      "GR",
		"Iso3":      "GRC",
		"Name":      "Greece",
		"Continent": "eu",
		"Prefix":    "30",
	},
	{
		"Iso2":      "GS",
		"Iso3":      "SGS",
		"Name":      "South Georgia and the South Sandwich Islands",
		"Continent": "an",
		"Prefix":    "500",
	},
	{
		"Iso2":      "GT",
		"Iso3":      "GTM",
		"Name":      "Guatemala",
		"Continent": "na",
		"Prefix":    "502",
	},
	{
		"Iso2":      "GU",
		"Iso3":      "GUM",
		"Name":      "Guam",
		"Continent": "oc",
		"Prefix":    "1671",
	},
	{
		"Iso2":      "GW",
		"Iso3":      "GNB",
		"Name":      "Guinea-Bissau",
		"Continent": "af",
		"Prefix":    "245",
	},
	{
		"Iso2":      "GY",
		"Iso3":      "GUY",
		"Name":      "Guyana",
		"Continent": "sa",
		"Prefix":    "592",
	},
	{
		"Iso2":      "HK",
		"Iso3":      "HKG",
		"Name":      "Hong Kong, (China)",
		"Continent": "as",
		"Prefix":    "852",
	},
	{
		"Iso2":      "HM",
		"Iso3":      "HMD",
		"Name":      "Heard Island and Mcdonald Islands",
		"Continent": "an",
		"Prefix":    "",
	},
	{
		"Iso2":      "HN",
		"Iso3":      "HND",
		"Name":      "Honduras",
		"Continent": "na",
		"Prefix":    "504",
	},
	{
		"Iso2":      "HR",
		"Iso3":      "HRV",
		"Name":      "Croatia",
		"Continent": "eu",
		"Prefix":    "385",
	},
	{
		"Iso2":      "HT",
		"Iso3":      "HTI",
		"Name":      "Haiti",
		"Continent": "na",
		"Prefix":    "509",
	},
	{
		"Iso2":      "HU",
		"Iso3":      "HUN",
		"Name":      "Hungary",
		"Continent": "eu",
		"Prefix":    "36",
	},
	{
		"Iso2":      "ID",
		"Iso3":      "IDN",
		"Name":      "Indonesia",
		"Continent": "as",
		"Prefix":    "62",
	},
	{
		"Iso2":      "IE",
		"Iso3":      "IRL",
		"Name":      "Ireland",
		"Continent": "eu",
		"Prefix":    "353",
	},
	{
		"Iso2":      "IL",
		"Iso3":      "ISR",
		"Name":      "Israel",
		"Continent": "as",
		"Prefix":    "972",
	},
	{
		"Iso2":      "IN",
		"Iso3":      "IND",
		"Name":      "India",
		"Continent": "as",
		"Prefix":    "91",
	},
	{
		"Iso2":      "IO",
		"Iso3":      "IOT",
		"Name":      "British Indian Ocean Territory",
		"Continent": "as",
		"Prefix":    "246",
	},
	{
		"Iso2":      "IQ",
		"Iso3":      "IRQ",
		"Name":      "Iraq",
		"Continent": "as",
		"Prefix":    "964",
	},
	{
		"Iso2":      "IR",
		"Iso3":      "IRN",
		"Name":      "Iran, Islamic Republic of",
		"Continent": "as",
		"Prefix":    "98",
	},
	{
		"Iso2":      "IS",
		"Iso3":      "ISL",
		"Name":      "Iceland",
		"Continent": "eu",
		"Prefix":    "354",
	},
	{
		"Iso2":      "IT",
		"Iso3":      "ITA",
		"Name":      "Italy",
		"Continent": "eu",
		"Prefix":    "39",
	},
	{
		"Iso2":      "JM",
		"Iso3":      "JAM",
		"Name":      "Jamaica",
		"Continent": "na",
		"Prefix":    "1876",
	},
	{
		"Iso2":      "JO",
		"Iso3":      "JOR",
		"Name":      "Jordan",
		"Continent": "as",
		"Prefix":    "962",
	},
	{
		"Iso2":      "JP",
		"Iso3":      "JPN",
		"Name":      "Japan",
		"Continent": "as",
		"Prefix":    "81",
	},
	{
		"Iso2":      "KE",
		"Iso3":      "KEN",
		"Name":      "Kenya",
		"Continent": "af",
		"Prefix":    "254",
	},
	{
		"Iso2":      "KG",
		"Iso3":      "KGZ",
		"Name":      "Kyrgyzstan",
		"Continent": "as",
		"Prefix":    "996",
	},
	{
		"Iso2":      "KH",
		"Iso3":      "KHM",
		"Name":      "Cambodia",
		"Continent": "as",
		"Prefix":    "855",
	},
	{
		"Iso2":      "KI",
		"Iso3":      "KIR",
		"Name":      "Kiribati",
		"Continent": "oc",
		"Prefix":    "686",
	},
	{
		"Iso2":      "KM",
		"Iso3":      "COM",
		"Name":      "Comoros",
		"Continent": "af",
		"Prefix":    "269",
	},
	{
		"Iso2":      "KN",
		"Iso3":      "KNA",
		"Name":      "Saint Kitts and Nevis",
		"Continent": "na",
		"Prefix":    "1869",
	},
	{
		"Iso2":      "KP",
		"Iso3":      "PRK",
		"Name":      "Korea, Democratic People's Republic of",
		"Continent": "as",
		"Prefix":    "850",
	},
	{
		"Iso2":      "KR",
		"Iso3":      "KOR",
		"Name":      "Korea, Republic of",
		"Continent": "as",
		"Prefix":    "82",
	},
	{
		"Iso2":      "KW",
		"Iso3":      "KWT",
		"Name":      "Kuwait",
		"Continent": "as",
		"Prefix":    "965",
	},
	{
		"Iso2":      "KY",
		"Iso3":      "CYM",
		"Name":      "Cayman Islands",
		"Continent": "na",
		"Prefix":    "1345",
	},
	{
		"Iso2":      "KZ",
		"Iso3":      "KAZ",
		"Name":      "Kazakhstan",
		"Continent": "as",
		"Prefix":    "7",
	},
	{
		"Iso2":      "LA",
		"Iso3":      "LAO",
		"Name":      "Lao People's Democratic Republic",
		"Continent": "as",
		"Prefix":    "856",
	},
	{
		"Iso2":      "LB",
		"Iso3":      "LBN",
		"Name":      "Lebanon",
		"Continent": "as",
		"Prefix":    "961",
	},
	{
		"Iso2":      "LC",
		"Iso3":      "LCA",
		"Name":      "Saint Lucia",
		"Continent": "na",
		"Prefix":    "1758",
	},
	{
		"Iso2":      "LI",
		"Iso3":      "LIE",
		"Name":      "Liechtenstein",
		"Continent": "eu",
		"Prefix":    "423",
	},
	{
		"Iso2":      "LK",
		"Iso3":      "LKA",
		"Name":      "Sri Lanka",
		"Continent": "as",
		"Prefix":    "94",
	},
	{
		"Iso2":      "LR",
		"Iso3":      "LBR",
		"Name":      "Liberia",
		"Continent": "af",
		"Prefix":    "231",
	},
	{
		"Iso2":      "LS",
		"Iso3":      "LSO",
		"Name":      "Lesotho",
		"Continent": "af",
		"Prefix":    "266",
	},
	{
		"Iso2":      "LT",
		"Iso3":      "LTY",
		"Name":      "Lithuania",
		"Continent": "eu",
		"Prefix":    "370",
	},
	{
		"Iso2":      "LU",
		"Iso3":      "LUX",
		"Name":      "Luxembourg",
		"Continent": "eu",
		"Prefix":    "352",
	},
	{
		"Iso2":      "LV",
		"Iso3":      "LVA",
		"Name":      "Latvia",
		"Continent": "eu",
		"Prefix":    "371",
	},
	{
		"Iso2":      "LY",
		"Iso3":      "LBY",
		"Name":      "Libyan Arab Jamahiriya",
		"Continent": "af",
		"Prefix":    "218",
	},
	{
		"Iso2":      "MA",
		"Iso3":      "MAR",
		"Name":      "Morocco",
		"Continent": "af",
		"Prefix":    "212",
	},
	{
		"Iso2":      "MC",
		"Iso3":      "MCO",
		"Name":      "Monaco",
		"Continent": "eu",
		"Prefix":    "377",
	},
	{
		"Iso2":      "MD",
		"Iso3":      "MDA",
		"Name":      "Moldova, Republic of",
		"Continent": "eu",
		"Prefix":    "373",
	},
	{
		"Iso2":      "ME",
		"Iso3":      "MNE",
		"Name":      "Montenegro",
		"Continent": "eu",
		"Prefix":    "382",
	},
	{
		"Iso2":      "MG",
		"Iso3":      "MDG",
		"Name":      "Madagascar",
		"Continent": "af",
		"Prefix":    "261",
	},
	{
		"Iso2":      "MH",
		"Iso3":      "MHL",
		"Name":      "Marshall Islands",
		"Continent": "oc",
		"Prefix":    "692",
	},
	{
		"Iso2":      "MK",
		"Iso3":      "MKD",
		"Name":      "Macedonia, the Former Yugoslav Republic of",
		"Continent": "eu",
		"Prefix":    "389",
	},
	{
		"Iso2":      "ML",
		"Iso3":      "MLI",
		"Name":      "Mali",
		"Continent": "af",
		"Prefix":    "223",
	},
	{
		"Iso2":      "MM",
		"Iso3":      "MMR",
		"Name":      "Myanmar",
		"Continent": "as",
		"Prefix":    "95",
	},
	{
		"Iso2":      "MN",
		"Iso3":      "MNG",
		"Name":      "Mongolia",
		"Continent": "as",
		"Prefix":    "976",
	},
	{
		"Iso2":      "MO",
		"Iso3":      "MAC",
		"Name":      "Macao, (China)",
		"Continent": "as",
		"Prefix":    "853",
	},
	{
		"Iso2":      "MP",
		"Iso3":      "MNP",
		"Name":      "Northern Mariana Islands",
		"Continent": "oc",
		"Prefix":    "1670",
	},
	{
		"Iso2":      "MQ",
		"Iso3":      "MTQ",
		"Name":      "Martinique",
		"Continent": "na",
		"Prefix":    "596",
	},
	{
		"Iso2":      "MR",
		"Iso3":      "MRT",
		"Name":      "Mauritania",
		"Continent": "af",
		"Prefix":    "222",
	},
	{
		"Iso2":      "MS",
		"Iso3":      "MSR",
		"Name":      "Montserrat",
		"Continent": "na",
		"Prefix":    "1664",
	},
	{
		"Iso2":      "MT",
		"Iso3":      "MLT",
		"Name":      "Malta",
		"Continent": "eu",
		"Prefix":    "356",
	},
	{
		"Iso2":      "MU",
		"Iso3":      "MUS",
		"Name":      "Mauritius",
		"Continent": "af",
		"Prefix":    "230",
	},
	{
		"Iso2":      "MV",
		"Iso3":      "MDV",
		"Name":      "Maldives",
		"Continent": "as",
		"Prefix":    "960",
	},
	{
		"Iso2":      "MW",
		"Iso3":      "MWI",
		"Name":      "Malawi",
		"Continent": "af",
		"Prefix":    "265",
	},
	{
		"Iso2":      "MX",
		"Iso3":      "MEX",
		"Name":      "Mexico",
		"Continent": "na",
		"Prefix":    "52",
	},
	{
		"Iso2":      "MY",
		"Iso3":      "MYS",
		"Name":      "Malaysia",
		"Continent": "as",
		"Prefix":    "60",
	},
	{
		"Iso2":      "MZ",
		"Iso3":      "MOZ",
		"Name":      "Mozambique",
		"Continent": "af",
		"Prefix":    "258",
	},
	{
		"Iso2":      "NA",
		"Iso3":      "NAM",
		"Name":      "Namibia",
		"Continent": "af",
		"Prefix":    "264",
	},
	{
		"Iso2":      "NC",
		"Iso3":      "NCL",
		"Name":      "New Caledonia",
		"Continent": "oc",
		"Prefix":    "687",
	},
	{
		"Iso2":      "NE",
		"Iso3":      "NER",
		"Name":      "Niger",
		"Continent": "af",
		"Prefix":    "227",
	},
	{
		"Iso2":      "NF",
		"Iso3":      "NFK",
		"Name":      "Norfolk Island",
		"Continent": "oc",
		"Prefix":    "672",
	},
	{
		"Iso2":      "NG",
		"Iso3":      "NGA",
		"Name":      "Nigeria",
		"Continent": "af",
		"Prefix":    "234",
	},
	{
		"Iso2":      "NI",
		"Iso3":      "NIC",
		"Name":      "Nicaragua",
		"Continent": "na",
		"Prefix":    "505",
	},
	{
		"Iso2":      "NL",
		"Iso3":      "NLD",
		"Name":      "Netherlands",
		"Continent": "eu",
		"Prefix":    "31",
	},
	{
		"Iso2":      "NO",
		"Iso3":      "NOR",
		"Name":      "Norway",
		"Continent": "eu",
		"Prefix":    "47",
	},
	{
		"Iso2":      "NP",
		"Iso3":      "NPL",
		"Name":      "Nepal",
		"Continent": "as",
		"Prefix":    "977",
	},
	{
		"Iso2":      "NR",
		"Iso3":      "NRU",
		"Name":      "Nauru",
		"Continent": "oc",
		"Prefix":    "674",
	},
	{
		"Iso2":      "NU",
		"Iso3":      "NIU",
		"Name":      "Niue",
		"Continent": "oc",
		"Prefix":    "683",
	},
	{
		"Iso2":      "NZ",
		"Iso3":      "NZL",
		"Name":      "New Zealand",
		"Continent": "oc",
		"Prefix":    "64",
	},
	{
		"Iso2":      "OM",
		"Iso3":      "OMN",
		"Name":      "Oman",
		"Continent": "as",
		"Prefix":    "968",
	},
	{
		"Iso2":      "PA",
		"Iso3":      "PAN",
		"Name":      "Panama",
		"Continent": "na",
		"Prefix":    "507",
	},
	{
		"Iso2":      "PE",
		"Iso3":      "PER",
		"Name":      "Peru",
		"Continent": "sa",
		"Prefix":    "51",
	},
	{
		"Iso2":      "PF",
		"Iso3":      "PYF",
		"Name":      "French Polynesia",
		"Continent": "oc",
		"Prefix":    "689",
	},
	{
		"Iso2":      "PG",
		"Iso3":      "PNG",
		"Name":      "Papua New Guinea",
		"Continent": "oc",
		"Prefix":    "675",
	},
	{
		"Iso2":      "PH",
		"Iso3":      "PHL",
		"Name":      "Philippines",
		"Continent": "as",
		"Prefix":    "63",
	},
	{
		"Iso2":      "PK",
		"Iso3":      "PAK",
		"Name":      "Pakistan",
		"Continent": "as",
		"Prefix":    "92",
	},
	{
		"Iso2":      "PL",
		"Iso3":      "POL",
		"Name":      "Poland",
		"Continent": "eu",
		"Prefix":    "48",
	},
	{
		"Iso2":      "PM",
		"Iso3":      "SPM",
		"Name":      "Saint Pierre and Miquelon",
		"Continent": "na",
		"Prefix":    "508",
	},
	{
		"Iso2":      "PN",
		"Iso3":      "PCN",
		"Name":      "Pitcairn",
		"Continent": "oc",
		"Prefix":    "64",
	},
	{
		"Iso2":      "PR",
		"Iso3":      "PRI",
		"Name":      "Puerto Rico",
		"Continent": "na",
		"Prefix":    "1787",
	},
	{
		"Iso2":      "PS",
		"Iso3":      "PSE",
		"Name":      "Palestinian Territory, Occupied",
		"Continent": "as",
		"Prefix":    "970",
	},
	{
		"Iso2":      "PT",
		"Iso3":      "PRT",
		"Name":      "Portugal",
		"Continent": "eu",
		"Prefix":    "351",
	},
	{
		"Iso2":      "PW",
		"Iso3":      "PLW",
		"Name":      "Palau",
		"Continent": "oc",
		"Prefix":    "680",
	},
	{
		"Iso2":      "PY",
		"Iso3":      "PRY",
		"Name":      "Paraguay",
		"Continent": "sa",
		"Prefix":    "595",
	},
	{
		"Iso2":      "QA",
		"Iso3":      "QAT",
		"Name":      "Qatar",
		"Continent": "as",
		"Prefix":    "974",
	},
	{
		"Iso2":      "RE",
		"Iso3":      "REU",
		"Name":      "Reunion",
		"Continent": "af",
		"Prefix":    "262",
	},
	{
		"Iso2":      "RO",
		"Iso3":      "ROU",
		"Name":      "Romania",
		"Continent": "eu",
		"Prefix":    "40",
	},
	{
		"Iso2":      "RS",
		"Iso3":      "SRB",
		"Name":      "Serbia",
		"Continent": "eu",
		"Prefix":    "381",
	},
	{
		"Iso2":      "RU",
		"Iso3":      "RUS",
		"Name":      "Russian Federation",
		"Continent": "eu",
		"Prefix":    "7",
	},
	{
		"Iso2":      "RW",
		"Iso3":      "RWA",
		"Name":      "Rwanda",
		"Continent": "af",
		"Prefix":    "250",
	},
	{
		"Iso2":      "SA",
		"Iso3":      "SAU",
		"Name":      "Saudi Arabia",
		"Continent": "as",
		"Prefix":    "966",
	},
	{
		"Iso2":      "SB",
		"Iso3":      "SLB",
		"Name":      "Solomon Islands",
		"Continent": "oc",
		"Prefix":    "677",
	},
	{
		"Iso2":      "SC",
		"Iso3":      "SYC",
		"Name":      "Seychelles",
		"Continent": "af",
		"Prefix":    "248",
	},
	{
		"Iso2":      "SD",
		"Iso3":      "SDN",
		"Name":      "Sudan",
		"Continent": "af",
		"Prefix":    "249",
	},
	{
		"Iso2":      "SE",
		"Iso3":      "SWE",
		"Name":      "Sweden",
		"Continent": "eu",
		"Prefix":    "46",
	},
	{
		"Iso2":      "SG",
		"Iso3":      "SGP",
		"Name":      "Singapore",
		"Continent": "as",
		"Prefix":    "65",
	},
	{
		"Iso2":      "SH",
		"Iso3":      "SHN",
		"Name":      "Saint Helena",
		"Continent": "af",
		"Prefix":    "290",
	},
	{
		"Iso2":      "SI",
		"Iso3":      "SVN",
		"Name":      "Slovenia",
		"Continent": "eu",
		"Prefix":    "386",
	},
	{
		"Iso2":      "SJ",
		"Iso3":      "SJM",
		"Name":      "Svalbard and Jan Mayen",
		"Continent": "eu",
		"Prefix":    "47",
	},
	{
		"Iso2":      "SK",
		"Iso3":      "SVK",
		"Name":      "Slovakia",
		"Continent": "eu",
		"Prefix":    "421",
	},
	{
		"Iso2":      "SL",
		"Iso3":      "SLE",
		"Name":      "Sierra Leone",
		"Continent": "af",
		"Prefix":    "232",
	},
	{
		"Iso2":      "SM",
		"Iso3":      "SMR",
		"Name":      "San Marino",
		"Continent": "eu",
		"Prefix":    "378",
	},
	{
		"Iso2":      "SN",
		"Iso3":      "SEN",
		"Name":      "Senegal",
		"Continent": "af",
		"Prefix":    "221",
	},
	{
		"Iso2":      "SO",
		"Iso3":      "SOM",
		"Name":      "Somalia",
		"Continent": "af",
		"Prefix":    "252",
	},
	{
		"Iso2":      "SR",
		"Iso3":      "SUR",
		"Name":      "Suriname",
		"Continent": "sa",
		"Prefix":    "597",
	},
	{
		"Iso2":      "ST",
		"Iso3":      "STP",
		"Name":      "Sao Tome and Principe",
		"Continent": "af",
		"Prefix":    "239",
	},
	{
		"Iso2":      "SV",
		"Iso3":      "SLV",
		"Name":      "El Salvador",
		"Continent": "na",
		"Prefix":    "503",
	},
	{
		"Iso2":      "SY",
		"Iso3":      "SYR",
		"Name":      "Syrian Arab Republic",
		"Continent": "as",
		"Prefix":    "963",
	},
	{
		"Iso2":      "SZ",
		"Iso3":      "SZ",
		"Name":      "Swaziland",
		"Continent": "af",
		"Prefix":    "41",
	},
	{
		"Iso2":      "TC",
		"Iso3":      "TCA",
		"Name":      "Turks and Caicos Islands",
		"Continent": "na",
		"Prefix":    "1649",
	},
	{
		"Iso2":      "TD",
		"Iso3":      "TCD",
		"Name":      "Chad",
		"Continent": "af",
		"Prefix":    "235",
	},
	{
		"Iso2":      "TF",
		"Iso3":      "ATF",
		"Name":      "French Southern Territories",
		"Continent": "an",
		"Prefix":    "689",
	},
	{
		"Iso2":      "TG",
		"Iso3":      "TGO",
		"Name":      "Togo",
		"Continent": "af",
		"Prefix":    "228",
	},
	{
		"Iso2":      "TH",
		"Iso3":      "THA",
		"Name":      "Thailand",
		"Continent": "as",
		"Prefix":    "66",
	},
	{
		"Iso2":      "TJ",
		"Iso3":      "TJK",
		"Name":      "Tajikistan",
		"Continent": "as",
		"Prefix":    "992",
	},
	{
		"Iso2":      "TK",
		"Iso3":      "TKL",
		"Name":      "Tokelau",
		"Continent": "oc",
		"Prefix":    "690",
	},
	{
		"Iso2":      "TL",
		"Iso3":      "TLS",
		"Name":      "Timor-Leste",
		"Continent": "as",
		"Prefix":    "670",
	},
	{
		"Iso2":      "TM",
		"Iso3":      "TKM",
		"Name":      "Turkmenistan",
		"Continent": "as",
		"Prefix":    "993",
	},
	{
		"Iso2":      "TN",
		"Iso3":      "TUN",
		"Name":      "Tunisia",
		"Continent": "af",
		"Prefix":    "216",
	},
	{
		"Iso2":      "TO",
		"Iso3":      "TON",
		"Name":      "Tonga",
		"Continent": "oc",
		"Prefix":    "676",
	},
	{
		"Iso2":      "TR",
		"Iso3":      "TUR",
		"Name":      "Turkey",
		"Continent": "as",
		"Prefix":    "90",
	},
	{
		"Iso2":      "TT",
		"Iso3":      "TTO",
		"Name":      "Trinidad and Tobago",
		"Continent": "na",
		"Prefix":    "1868",
	},
	{
		"Iso2":      "TV",
		"Iso3":      "TUV",
		"Name":      "Tuvalu",
		"Continent": "oc",
		"Prefix":    "688",
	},
	{
		"Iso2":      "TW",
		"Iso3":      "TWN",
		"Name":      "Taiwan",
		"Continent": "as",
		"Prefix":    "886",
	},
	{
		"Iso2":      "TZ",
		"Iso3":      "TZA",
		"Name":      "Tanzania, United Republic of",
		"Continent": "af",
		"Prefix":    "255",
	},
	{
		"Iso2":      "UG",
		"Iso3":      "UGA",
		"Name":      "Uganda",
		"Continent": "af",
		"Prefix":    "256",
	},
	{
		"Iso2":      "UK",
		"Iso3":      "UKR",
		"Name":      "Ukraine",
		"Continent": "eu",
		"Prefix":    "380",
	},
	{
		"Iso2":      "UM",
		"Iso3":      "UMI",
		"Name":      "United States Minor Outlying Islands",
		"Continent": "na",
		"Prefix":    "699",
	},
	{
		"Iso2":      "US",
		"Iso3":      "USA",
		"Name":      "United States",
		"Continent": "na",
		"Prefix":    "1",
	},
	{
		"Iso2":      "UY",
		"Iso3":      "URY",
		"Name":      "Uruguay",
		"Continent": "sa",
		"Prefix":    "598",
	},
	{
		"Iso2":      "UZ",
		"Iso3":      "UZB",
		"Name":      "Uzbekistan",
		"Continent": "as",
		"Prefix":    "998",
	},
	{
		"Iso2":      "VA",
		"Iso3":      "VAT",
		"Name":      "Vatican City State (Holly See)",
		"Continent": "eu",
		"Prefix":    "379",
	},
	{
		"Iso2":      "VC",
		"Iso3":      "VCT",
		"Name":      "Saint Vincent and the Grenadines",
		"Continent": "na",
		"Prefix":    "1784",
	},
	{
		"Iso2":      "VE",
		"Iso3":      "VEN",
		"Name":      "Venezuela",
		"Continent": "sa",
		"Prefix":    "58",
	},
	{
		"Iso2":      "VG",
		"Iso3":      "VGB",
		"Name":      "Virgin Islands, British",
		"Continent": "na",
		"Prefix":    "1284",
	},
	{
		"Iso2":      "VI",
		"Iso3":      "VIR",
		"Name":      "Virgin Islands, U.S.",
		"Continent": "na",
		"Prefix":    "1340",
	},
	{
		"Iso2":      "VN",
		"Iso3":      "VNM",
		"Name":      "Viet Nam",
		"Continent": "as",
		"Prefix":    "84",
	},
	{
		"Iso2":      "VU",
		"Iso3":      "VUT",
		"Name":      "Vanuatu",
		"Continent": "oc",
		"Prefix":    "678",
	},
	{
		"Iso2":      "WF",
		"Iso3":      "WLF",
		"Name":      "Wallis and Futuna",
		"Continent": "oc",
		"Prefix":    "681",
	},
	{
		"Iso2":      "WS",
		"Iso3":      "WSM",
		"Name":      "Samoa",
		"Continent": "oc",
		"Prefix":    "685",
	},
	{
		"Iso2":      "XK",
		"Iso3":      "XKX",
		"Name":      "Kosovo",
		"Continent": "eu",
		"Prefix":    "381",
	},
	{
		"Iso2":      "YE",
		"Iso3":      "YEM",
		"Name":      "Yemen",
		"Continent": "as",
		"Prefix":    "967",
	},
	{
		"Iso2":      "YT",
		"Iso3":      "MYT",
		"Name":      "Mayotte",
		"Continent": "af",
		"Prefix":    "262",
	},
	{
		"Iso2":      "ZA",
		"Iso3":      "ZAF",
		"Name":      "South Africa",
		"Continent": "af",
		"Prefix":    "27",
	},
	{
		"Iso2":      "ZM",
		"Iso3":      "ZMB",
		"Name":      "Zambia",
		"Continent": "af",
		"Prefix":    "260",
	},
	{
		"Iso2":      "ZW",
		"Iso3":      "ZWE",
		"Name":      "Zimbabwe",
		"Continent": "af",
		"Prefix":    "263",
	},
}

func (store *Store) seedCountriesIfTableIsEmpty() error {
	list, err := store.CountryList(CountryQueryOptions{
		Limit: 1,
	})

	if err != nil {
		return err
	}

	if len(list) > 0 {
		return nil
	}

	for _, entry := range countries {
		country := NewCountry()
		country.SetIsoCode2(entry["Iso2"])
		country.SetIsoCode3(entry["Iso3"])
		country.SetName(entry["Name"])
		country.SetContinent(entry["Continent"])
		country.SetPhonePrefix(entry["Prefix"])

		err = store.CountryCreate(country)

		if err != nil {
			return err
		}
	}

	return nil
}
